import { create } from "zustand";
import { persist } from "zustand/middleware";

type Lang = "ar" | "en";

interface LangState {
  lang: Lang;
  setLang: (lang: Lang) => void;
  isRTL: () => boolean;
}

export const useLangStore = create<LangState>()(
  persist(
    (set, get) => ({
      lang: "ar",
      setLang: (lang) => {
        set({ lang });
        if (typeof document !== "undefined") {
          document.documentElement.lang = lang;
          document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
        }
      },
      isRTL: () => get().lang === "ar",
    }),
    { name: "motionhr_language" }
  )
);

export const dict = {
  ar: {
    // Landing Page
    landingNav1: "ليه MotionHR؟",
    landingNav2: "المميزات",
    landingNav3: "التجربة",
    landingNav4: "تواصل",
    landingNavDemo: "جرّب النسخة",
    landingNavCTA: "احجز ديمو",
    landingBadge: "نظام واحد يربط التشغيل اليومي بالمرتبات والإدارة",
    landingH1a: "من أول حضور الموظف",
    landingH1b: "لحد صافي المرتب",
    landingH1c: "كل تشغيل شركتك في مكان واحد",
    landingSubtitle: "MotionHR مش مجرد HR System. ده نظام تشغيل فعلي للشركة: حضور، طلبات، إجازات، مأموريات، فرق ميدانية، سياسات، مرتبات، وتقارير تنفيذية — في تجربة واحدة مرتبة وسريعة.",
    landingCTA1: "اتكلم معايا على واتساب",
    landingCTA2: "جرّب النسخة التجريبية",
    landingCheck1: "حضور + GPS + فرق ميدانية",
    landingCheck2: "مرتبات + بدلات + خصومات",
    landingCheck3: "موافقات المدير و HR",
    landingCheck4: "تصدير Excel / PDF",
    landingPainTitle: "لو عندك واحدة من المشاكل دي،",
    landingPainTitleAccent: "MotionHR معمول لك",
    landingPainSubtitle: "إحنا بنحل الفجوة اللي بتحصل بين التشغيل اليومي، متابعة المدير، وسيطرة الإدارة على المرتبات والتقارير.",
    landingFeaturesTitle: "كل اللي تحتاجه لإدارة التشغيل اليومي",
    landingFeaturesSubtitle: "من أول حضور الموظف لحد تصدير كشف المرتبات والتقارير — من غير لف ودوران.",
    landingPortalsTitle: "3 بوابات في نظام واحد",
    landingPortalsSubtitle: "كل دور في الشركة له تجربة مصممة له بالظبط: موظف، مدير، وموارد بشرية.",
    landingWorkflowTitle: "من أول اليوم لآخر الشهر",
    landingWorkflowSubtitle: "MotionHR بيربط التشغيل الحقيقي للشركة في فلو واحد واضح: متابعة يومية، قرارات أسرع، ومرتبات محسوبة على بيانات فعلية.",
    landingDemoTitle: "لو عايز تشوف النظام فعلاً، جرّبه أو كلمني الآن",
    landingDemoSubtitle: "تقدر تدخل تشوف الواجهة، أو تبعتلي على واتساب وأرتب لك عرض مباشر سريع على نفس الحالة الحقيقية للنظام.",
    landingDemo1Title: "نسخة تجريبية",
    landingDemo1Desc: "ادخل على النظام وشوف التدفقات الرئيسية: حضور، طلبات، هيكل تنظيمي، وتقارير.",
    landingDemo1Btn: "جرّب النسخة الآن",
    landingDemo2Title: "عرض مباشر مع المطور",
    landingDemo2Desc: "لو عايز أعرفك على النظام حسب نشاط شركتك، ابعتلي على واتساب مباشرة.",
    landingDemo2Btn: "احجز ديمو واتساب",
    landingContactTitle: "جاهز تشوف MotionHR على شركتك؟",
    landingContactSubtitle: "أسرع طريقة دلوقتي: ابعت رسالة واتساب، أو راسلنا على الإيميل، أو ادخل النسخة التجريبية.",
    landingWA: "واتساب مباشر",
    landingWADesc: "أسرع قناة تواصل لو عايز رد سريع أو حجز ديمو.",
    landingMail: "البريد الإلكتروني",
    landingMailDesc: "مناسب لو عايز تبعت تفاصيل شركتك أو طلب رسمي.",
    landingDemoCard: "جرّب النظام",
    landingDemoCardDesc: "ادخل على النسخة وشوف تجربة النظام بنفسك.",
    landingFloatingWA: "تواصل واتساب",
    landingDemoReady: "Demo Ready",
    landingFooter: "Designed & Developed by",
    // Sidebar
    dashboard: "الرئيسية",
    employees: "الموظفون",
    attendance: "الحضور والانصراف",
    leaves: "الإجازات",
    requests: "الطلبات",
    payroll: "الرواتب",
    payrollRuns: "تشغيل المرتبات",
    manualEntries: "الإدخالات اليدوية",
    missions: "المهمات",
    locations: "المواقع المباشرة",
    announcements: "الإعلانات",
    departments: "الأقسام",
    branches: "الفروع",
    shifts: "الشيفتات",
    jobTitles: "المسميات الوظيفية",
    company: "الشركة",
    settings: "الإعدادات",
    trustedDevices: "الأجهزة المعتمدة",
    importEmployees: "استيراد الموظفين",
    myTeam: "فريقي",
    myAttendance: "حضوري",
    myLeaves: "إجازاتي",
    myRequests: "طلباتي",
    myMissions: "مهماتي",
    myPayslip: "كشف مرتبي",
    myProfile: "ملفي الشخصي",
    myPermissions: "أذوناتي",
    myFieldVisits: "زياراتي الميدانية",
    notifications: "الإشعارات",
    companyRegulations: "اللائحة التنظيمية",
    reports: "التقارير",
    // Header
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    search: "بحث سريع...",
    // Dashboard
    totalEmployees: "إجمالي الموظفين",
    presentToday: "الحاضرون اليوم",
    onLeave: "في إجازة",
    pendingRequests: "طلبات معلقة",
    comingSoon: "قريباً",
    activeEmployees: "الموظفون النشطون",
    quickActions: "إجراءات سريعة",
    recentActivity: "النشاطات الأخيرة",
    noActivity: "لا يوجد نشاط بعد",
    noActivityDesc: "سيظهر هنا سجل النشاطات قريباً",
    welcome: "مرحباً",
    overview: "نظرة عامة على",
    // Shared
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    cancel: "إلغاء",
    save: "حفظ",
    saving: "جارِ الحفظ...",
    create: "إنشاء",
    noResults: "لم يتم العثور على نتائج",
    active: "نشط",
    inactive: "غير نشط",
    employee_count: "موظف",
    average: "متوسط",
    total: "إجمالي",
    // Departments
    addDepartment: "إضافة قسم",
    departmentsTitle: "الأقسام",
    departmentsDesc: "إدارة الأقسام في الشركة",
    totalDepartments: "إجمالي الأقسام",
    avgEmployeesPerDept: "متوسط الموظفين/قسم",
    searchDepartments: "بحث في الأقسام...",
    noDepartments: "لا يوجد أقسام بعد",
    addFirstDept: "إضافة أول قسم",
    addDeptTitle: "إضافة قسم جديد",
    addDeptDesc: "أدخل بيانات القسم الجديد",
    deptNameAr: "اسم القسم بالعربي *",
    deptNameEn: "اسم القسم بالإنجليزي",
    deptDesc: "الوصف",
    deptDescPlaceholder: "وصف مختصر للقسم...",
    createDept: "إنشاء القسم",
    failedLoad: "فشل تحميل البيانات",
    failedCreate: "فشل إنشاء القسم",
    createdSuccess: "تم إنشاء القسم بنجاح",
    nameArRequired: "اسم القسم بالعربي مطلوب",
    // Branches
    addBranch: "إضافة فرع",
    branchesTitle: "الفروع",
    branchesDesc: "إدارة فروع الشركة",
    totalBranches: "إجمالي الفروع",
    avgEmployeesPerBranch: "متوسط الموظفين/فرع",
    searchBranches: "بحث في الفروع...",
    noBranches: "لا يوجد فروع بعد",
    addFirstBranch: "إضافة أول فرع",
    addBranchTitle: "إضافة فرع جديد",
    addBranchDesc: "أدخل بيانات الفرع الجديد",
    branchNameAr: "اسم الفرع بالعربي *",
    branchNameEn: "اسم الفرع بالإنجليزي",
    branchAddress: "العنوان",
    branchPhone: "رقم الهاتف",
    createBranch: "إنشاء الفرع",
    mainBranch: "فرع رئيسي",
    failedCreateBranch: "فشل إنشاء الفرع",
    createdBranchSuccess: "تم إنشاء الفرع بنجاح",
    branchNameArRequired: "اسم الفرع بالعربي مطلوب",
    // Shifts
    addShift: "إضافة شيفت",
    shiftsTitle: "الشيفتات",
    shiftsDesc: "إدارة شيفتات العمل",
    totalShifts: "إجمالي الشيفتات",
    defaultShift: "الشيفت الافتراضي",
    activeShifts: "النشطة",
    searchShifts: "بحث في الشيفتات...",
    noShifts: "لا يوجد شيفتات بعد",
    addFirstShift: "إضافة أول شيفت",
    shiftFixed: "ثابت",
    shiftFlex: "مرن",
    shiftOpen: "مفتوح",
    shiftStart: "البداية",
    shiftEnd: "النهاية",
    shiftHours: "ساعات",
    shiftGrace: "سماح",
    shiftBreak: "راحة",
    shiftMin: "د",
    assignEmployees: "تعيين موظفين",
    failedCreateShift: "فشل إنشاء الشيفت",
    createdShiftSuccess: "تم إنشاء الشيفت بنجاح",
    shiftNameRequired: "اسم الشيفت مطلوب",
    // Job Titles
    addJobTitle: "إضافة مسمى",
    jobTitlesTitle: "المسميات الوظيفية",
    jobTitlesDesc: "إدارة الوظائف والمناصب",
    totalJobTitles: "إجمالي المسميات",
    avgEmployeesPerTitle: "متوسط الموظفين/مسمى",
    searchJobTitles: "بحث في المسميات...",
    noJobTitles: "لا يوجد مسميات بعد",
    addFirstJobTitle: "إضافة أول مسمى",
    addJobTitleDialog: "إضافة مسمى وظيفي",
    addJobTitleDesc: "أدخل بيانات المسمى الجديد",
    jobTitleNameAr: "الاسم بالعربي *",
    jobTitleNameEn: "الاسم بالإنجليزي",
    jobTitleDescLabel: "الوصف",
    createJobTitle: "إنشاء",
    failedCreateTitle: "فشل الإنشاء",
    createdTitleSuccess: "تم إنشاء المسمى بنجاح",
    titleNameArRequired: "اسم المسمى بالعربي مطلوب",
    // Employees List
    employeesTitle: "الموظفون",
    employeesDesc: "إدارة جميع موظفي الشركة",
    activeEmployeesCount: "النشطون",
    inactiveEmployees: "غير نشط",
    importBtn: "استيراد",
    addEmployee: "إضافة موظف",
    searchEmployees: "بحث بالاسم، الكود، الموبايل، الرقم القومي...",
    allDepts: "كل الأقسام",
    allStatuses: "كل الحالات",
    statusActive: "نشط",
    statusInactive: "غير نشط",
    statusOnLeave: "في إجازة",
    statusTerminated: "منتهي",
    statusResigned: "مستقيل",
    colEmployee: "الموظف",
    colCode: "الكود",
    colDept: "القسم",
    colJobTitle: "المسمى الوظيفي",
    colBranch: "الفرع",
    colPhone: "الموبايل",
    colStatus: "الحالة",
    noEmployees: "لا يوجد موظفون",
    failedLoadEmployees: "فشل تحميل قائمة الموظفين",
    showingOf: "عرض",
    of: "من",
    ofTotal: "من إجمالي",
    deptFilter: "القسم",
    statusFilter: "الحالة",
    // Employee Detail
    employeeNotFound: "الموظف غير موجود",
    backToList: "العودة للقائمة",
    backToEmployees: "العودة للموظفين",
    personalInfo: "بيانات شخصية",
    jobInfo: "الوظيفة",
    salaryInfo: "المرتب",
    contractInfo: "العقد",
    nameAr: "الاسم بالعربي",
    nameEn: "الاسم بالإنجليزي",
    nationalId: "الرقم القومي",
    birthDate: "تاريخ الميلاد",
    gender: "النوع",
    maritalStatus: "الحالة الاجتماعية",
    religion: "الديانة",
    nationality: "الجنسية",
    contactInfo: "التواصل",
    phone: "الموبايل",
    phone2: "موبايل إضافي",
    email: "البريد الإلكتروني",
    city: "المدينة",
    addressField: "العنوان",
    empCode: "كود الموظف",
    hireDate: "تاريخ التعيين",
    dept: "القسم",
    branch: "الفرع",
    jobTitle: "المسمى الوظيفي",
    directManager: "المدير المباشر",
    attendancePattern: "نمط الحضور",
    workerType: "تصنيف الموظف",
    empStatus: "الحالة الوظيفية",
    basicSalary: "الراتب الأساسي",
    currency: "العملة",
    bankName: "البنك",
    bankAccount: "رقم الحساب",
    iban: "IBAN",
    contractType: "نوع العقد",
    contractStart: "بداية العقد",
    contractEnd: "نهاية العقد",
    // Import Page
    importTitle: "استيراد الموظفين",
    importDesc: "ارفع ملف Excel لإضافة أو تحديث موظفين بالجملة",
    uploadFile: "رفع الملف",
    downloadTemplate: "تحميل النموذج",
    dragDrop: "اسحب وأفلت الملف هنا",
    orClick: "أو اضغط للاختيار من الجهاز",
    maxSize: "حد أقصى 10 ميجا",
    startImport: "بدء الاستيراد",
    uploading: "جارِ الرفع...",
    importSuccess: "تم الاستيراد بنجاح",
    importFailed: "فشل الاستيراد",
    newEmployees: "موظف جديد",
    updatedEmployees: "تحديث",
    errors: "أخطاء",
    errorDetails: "تفاصيل الأخطاء",
    row: "صف",
    selectExcel: "يجب اختيار ملف Excel (.xlsx أو .xls)",
    fileTooLarge: "حجم الملف كبير جداً (الحد الأقصى 10 ميجا)",
    templateDownloaded: "تم تحميل النموذج بنجاح",
    templateFailed: "فشل تحميل النموذج",
    serverError: "خطأ في الاتصال بالسيرفر",
    upTo500: "حتى 500 موظف",
    perBatch: "في المرة الواحدة",
    fields67: "67 حقل",
    comprehensiveData: "بيانات شاملة لكل موظف",
    autoValidation: "تحقق تلقائي",
    validationDesc: "من صحة البيانات قبل الحفظ",
    kb: "كيلوبايت",
    importInstructions: "تعليمات الاستيراد",
    step1: "حمّل النموذج",
    step1Desc: "اضغط على تحميل النموذج للحصول على الشيت",
    step2: "املأ البيانات",
    step2Desc: "أدخل بيانات الموظفين في الشيت",
    step3: "ارفع الملف",
    step3Desc: "ارفع الملف المكتمل هنا",
    importNotes: "ملاحظات",
    note1: "الحقول المميزة بـ * إجبارية",
    note2: "الرقم القومي لازم يكون 14 رقم",
    note3: "التواريخ بصيغة YYYY-MM-DD",
    note4: "الموبايل بصيغة 01XXXXXXXXX",
    // Payroll
    payrollTitle: "الرواتب",
    payrollDesc: "إدارة رواتب الموظفين",
    selectMonth: "الشهر",
    selectYear: "السنة",
    grandTotalSalary: "إجمالي الرواتب",
    grandTotalAllowances: "إجمالي البدلات",
    grandTotalOvertime: "إجمالي الإضافي",
    grandTotalBonuses: "إجمالي المكافآت",
    grandTotalDeductions: "إجمالي الخصومات",
    grandTotalNet: "الصافي المستحق",
    empName: "اسم الموظف",
    basicSalaryCol: "الأساسي",
    allowancesCol: "البدلات",
    bonusesCol: "المكافآت",
    overtimeCol: "الإضافي",
    deductionsCol: "الخصومات",
    netSalaryCol: "الصافي",
    searchPayroll: "بحث بالاسم أو الكود...",
    noPayrollData: "لا يوجد بيانات رواتب لهذا الشهر",
    workingDays: "أيام العمل",
    presentDays: "أيام الحضور",
    absentDays: "أيام الغياب",
    lateMinutes: "دقائق التأخير",
    overtimeHours: "ساعات إضافية",
    onLeaveDays: "أيام إجازة",
    missionDays: "أيام مهمة",
    exportExcel: "تصدير Excel",
    exportPDF: "تصدير PDF",
    viewPayslip: "عرض كشف المرتب",
    payslipTitle: "كشف مرتب",
    forEmployee: "للموظف",
    forMonth: "لشهر",
    salaryBreakdown: "تفصيل الراتب",
    attendanceSummary: "ملخص الحضور",
    deductionsBreakdown: "تفصيل الخصومات",
    lateDeduction: "خصم التأخير",
    absenceDeduction: "خصم الغياب",
    earlyLeaveDeduction: "خصم الانصراف المبكر",
    insuranceDeduction: "خصم التأمين",
    installments: "أقساط",
    penalties: "جزاءات",
    extraDeductions: "خصومات إضافية",
    nightAllowance: "بدل ليلي",
    weekendAllowance: "بدل نهاية الأسبوع",
    fieldAllowance: "بدل ميداني",
    grossSalary: "الراتب الإجمالي",
    monthlyComparison: "مقارنة شهرية",
    monthlyComparisonDesc: "مقارنة الرواتب بين الشهور",
    advancedFilters: "فلاتر متقدمة",
    filterByBranch: "فلترة حسب الفرع",
    filterByDept: "فلترة حسب القسم",
    payrollAnalytics: "تحليلات الرواتب",
    salaryDistribution: "توزيع الرواتب",
    topPaid: "أعلى رواتب",
    payrollTrends: "اتجاهات الرواتب",
    bulkPayment: "دفع جماعي",
    processPayment: "معالجة الدفع",
    January: "يناير",
    February: "فبراير",
    March: "مارس",
    April: "أبريل",
    May: "مايو",
    June: "يونيو",
    July: "يوليو",
    August: "أغسطس",
    September: "سبتمبر",
    October: "أكتوبر",
    November: "نوفمبر",
    December: "ديسمبر",
    // Attendance
    attendanceTitle: "الحضور والانصراف",
    attendanceDesc: "متابعة حضور وانصراف الموظفين",
    selectDate: "اختر التاريخ",
    today: "اليوم",
    yesterday: "أمس",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    statusPresent: "حاضر",
    statusLate: "متأخر",
    statusAbsent: "غائب",
    statusOnLeaveAtt: "في إجازة",
    statusWeekend: "إجازة أسبوعية",
    statusMission: "مهمة",
    statusNoData: "لا يوجد بيانات",
    checkIn: "الحضور",
    checkOut: "الانصراف",
    workHours: "ساعات العمل",
    lateMinutesCol: "دقائق التأخير",
    earlyLeaveMinutes: "دقائق الانصراف المبكر",
    overtimeHoursCol: "ساعات إضافية",
    shiftName: "الشيفت",
    nightShift: "شيفت ليلي",
    weekendWork: "عمل نهاية أسبوع",
    filterByStatus: "فلترة حسب الحالة",
    allStatusesAtt: "كل الحالات",
    monthlyReport: "التقرير الشهري",
    dailyReport: "التقرير اليومي",
    noAttendanceData: "لا يوجد بيانات حضور لهذا اليوم",
    totalPresent: "إجمالي الحاضرين",
    totalLate: "إجمالي المتأخرين",
    totalAbsent: "إجمالي الغائبين",
    totalOnLeave: "إجمالي الإجازات",
    totalWeekend: "إجازة أسبوعية",
    totalMission: "في مهمة",
    exportAttendance: "تصدير الحضور",
    // Leaves
    leavesTitle: "الإجازات",
    leavesDesc: "متابعة إجازات الموظفين والأرصدة",
    totalLeaves: "إجمالي الإجازات",
    approvedLeaves: "مقبولة",
    pendingLeaves: "معلقة",
    rejectedLeaves: "مرفوضة",
    leaveTypesTitle: "أنواع الإجازات",
    leaveTypeName: "نوع الإجازة",
    daysAllowed: "الرصيد الكلي",
    daysUsed: "المستخدم",
    daysPending: "معلق",
    daysRemaining: "المتبقي",
    balancesTitle: "أرصدة الموظفين",
    colBalance: "الرصيد",
    colUsed: "المستخدم",
    colRemaining: "المتبقي",
    colUnpaid: "بدون مرتب",
    colHalfDay: "نصف يوم",
    noLeavesData: "لا يوجد بيانات إجازات",
    leaveCategoryAnnual: "سنوية",
    leaveCategorySick: "مرضية",
    leaveCategoryEmergency: "طارئة",
    leaveCategoryUnpaid: "بدون مرتب",
    leaveCategoryMaternity: "أمومة",
    leaveCategoryOther: "أخرى",
    daysUnit: "يوم",
    viewLeaveDetails: "عرض التفاصيل",
    addLeave: "إضافة إجازة",
    leaveStatus: "حالة الإجازة",
    leaveApproved: "مقبولة",
    leavePending: "معلقة",
    leaveRejected: "مرفوضة",
    leaveType: "النوع",
    leaveDates: "التواريخ",
    leaveReason: "السبب",
    // Requests
    requestsTitle: "الطلبات",
    requestsDesc: "متابعة طلبات الموظفين والموافقات",
    totalRequests: "إجمالي الطلبات",
    approvedRequests: "مقبولة",
    pendingRequestsCount: "معلقة",
    rejectedRequests: "مرفوضة",
    requestCategories: "أقسام الطلبات",
    requestTypes: "أنواع الطلبات",
    tabAllRequests: "كل الطلبات",
    tabPendingOnly: "معلقة فقط",
    requestType: "نوع الطلب",
    requestDate: "تاريخ الطلب",
    requestStatus: "الحالة",
    requestActions: "الإجراءات",
    approveBtn: "قبول",
    rejectBtn: "رفض",
    viewDetails: "تفاصيل",
    reqApproved: "مقبول",
    reqPending: "معلق",
    reqRejected: "مرفوض",
    reqCancelled: "ملغى",
    noRequestsData: "لا يوجد طلبات",
    typesInCategory: "نوع",
    requestReason: "السبب",
    requestAmount: "المبلغ",
    requestFrom: "من",
    requestTo: "إلى",
    submittedBy: "مقدم من",
    submittedAt: "قُدم في",
    // Reports
    reportsTitle: "التقارير",
    reportsDesc: "تقارير شاملة عن الموظفين والحضور والرواتب",
    reportsCategoryAttendance: "تقارير الحضور",
    reportsCategoryLeaves: "تقارير الإجازات",
    reportsCategoryPayroll: "تقارير الرواتب",
    reportsCategoryOther: "تقارير أخرى",
    // Individual Reports
    reportDailyAttendance: "الحضور اليومي",
    reportDailyAttendanceDesc: "متابعة حضور الموظفين يومياً",
    reportMonthlyAttendance: "الحضور الشهري",
    reportMonthlyAttendanceDesc: "ملخص حضور الشهر لكل موظف",
    reportLate: "التأخير",
    reportLateDesc: "الموظفون المتأخرون ومدة التأخير",
    reportAbsence: "الغياب",
    reportAbsenceDesc: "أيام الغياب لكل موظف",
    reportLeaves: "الإجازات",
    reportLeavesDesc: "تقرير مبسط للإجازات",
    reportLeavesEnhanced: "الإجازات (مفصل)",
    reportLeavesEnhancedDesc: "تقرير شامل مع الأرصدة",
    reportWorkHours: "ساعات العمل",
    reportWorkHoursDesc: "ساعات العمل الفعلية والإضافية",
    reportRequests: "الطلبات",
    reportRequestsDesc: "طلبات الموظفين وحالتها",
    reportPayrollAll: "الرواتب",
    reportPayrollAllDesc: "تقرير الرواتب الشهرية",
    reportPermissions: "الأذونات",
    reportPermissionsDesc: "أذونات التأخير والانصراف المبكر",
    reportShifts: "الشيفتات",
    reportShiftsDesc: "توزيع الموظفين على الشيفتات",
    reportExports: "التصدير",
    reportExportsDesc: "تصدير التقارير PDF و Excel",
    openReport: "فتح التقرير",
    comingSoonReport: "قريباً",
    // Absence Report
    absenceReportTitle: "تقرير الغياب",
    absenceReportDesc: "تفاصيل الغياب الشهري للموظفين",
    backToReports: "العودة للتقارير",
    totalWorkingDaysInMonth: "أيام العمل في الشهر",
    totalEmployeesWithAbsence: "موظفون فيهم غياب",
    totalAbsenceDays: "إجمالي أيام الغياب",
    absenceRate: "نسبة الغياب",
    colAttendedDays: "أيام الحضور",
    colAbsentDays: "أيام الغياب",
    colAbsentDates: "تواريخ الغياب",
    viewAllDates: "عرض كل التواريخ",
    hideAllDates: "إخفاء التواريخ",
    period: "الفترة",
    noAbsenceData: "لا يوجد بيانات غياب",
    absenceRateHigh: "غياب مرتفع",
    absenceRateMedium: "غياب متوسط",
    absenceRateLow: "غياب منخفض",
    // Late Report
    lateReportTitle: "تقرير التأخير",
    lateReportDesc: "تفاصيل التأخير الشهري للموظفين",
    totalEmployeesWithLate: "موظفون فيهم تأخير",
    totalLateDays: "إجمالي أيام التأخير",
    totalLateMinutesReport: "إجمالي دقائق التأخير",
    avgLateMinutes: "متوسط التأخير",
    colLateDays: "أيام التأخير",
    colLateMinutes: "دقائق التأخير",
    colAvgLate: "متوسط التأخير/يوم",
    colLateDates: "تواريخ التأخير",
    noLateData: "لا يوجد بيانات تأخير",
    lateSeverityHigh: "تأخير مرتفع",
    lateSeverityMedium: "تأخير متوسط",
    lateSeverityLow: "تأخير منخفض",
    minutes: "دقيقة",
    // Work Hours Report
    workHoursReportTitle: "تقرير ساعات العمل",
    workHoursReportDesc: "إجمالي ساعات العمل الفعلية للموظفين",
    totalHoursMonth: "إجمالي الساعات",
    totalDaysWorked: "أيام العمل الفعلية",
    avgHoursPerDay: "متوسط الساعات/يوم",
    colTotalHours: "إجمالي الساعات",
    colDaysWorked: "الأيام",
    colAvgHours: "المتوسط/يوم",
    colDailyBreakdown: "التفصيل اليومي",
    noWorkHoursData: "لا يوجد بيانات ساعات عمل",
    hoursUnit: "ساعة",
    productivity: "الإنتاجية",
    productivityHigh: "إنتاجية عالية",
    productivityMedium: "إنتاجية متوسطة",
    productivityLow: "إنتاجية منخفضة",
    // Permissions Report
    permissionsReportTitle: "تقرير الأذونات",
    permissionsReportDesc: "أذونات التأخير والانصراف المبكر للموظفين",
    maxHoursPerMonth: "الحد الأقصى الشهري",
    maxTimesPerMonth: "عدد المرات المسموحة",
    usedHours: "الساعات المستخدمة",
    usedTimes: "المرات المستخدمة",
    remainingHours: "الساعات المتبقية",
    colMaxHours: "الحد الأقصى",
    colUsedMinutes: "المستخدم (دقائق)",
    colUsedHours: "المستخدم (ساعات)",
    colMovementsCount: "عدد الحركات",
    colMovements: "التفاصيل",
    noPermissionsData: "لا يوجد بيانات أذونات",
    permissionMovement: "حركة",
    movements_word: "حركة",
    percentageUsed: "نسبة الاستخدام",
    usageHigh: "استخدام مرتفع",
    usageMedium: "استخدام متوسط",
    usageLow: "استخدام منخفض",
    // Monthly Attendance Report
    monthlyAttReportTitle: "تقرير الحضور الشهري",
    monthlyAttReportDesc: "ملخص حضور شهري لكل موظف",
    totalCheckins: "إجمالي تسجيلات الحضور",
    totalCheckouts: "إجمالي تسجيلات الانصراف",
    totalMonthDays: "أيام الشهر",
    colCheckins: "الحضور",
    colCheckouts: "الانصراف",
    colWorkingDays: "أيام العمل",
    colMonthDays: "أيام الشهر",
    colAttendanceRate: "نسبة الحضور",
    noMonthlyAttData: "لا يوجد بيانات حضور شهرية",
    attRateExcellent: "ممتاز",
    attRateGood: "جيد",
    attRateAverage: "متوسط",
    attRatePoor: "ضعيف",
    // Leaves Basic Report
    leavesBasicTitle: "تقرير الإجازات",
    leavesBasicDesc: "تقرير مبسط للإجازات المقدمة",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    leaveDaysCount: "عدد الأيام",
    colLeaveType: "نوع الإجازة",
    colStartDate: "من",
    colEndDate: "إلى",
    colDaysCount: "الأيام",
    colLeaveStatus: "الحالة",
    filterAll: "الكل",
    // Export
    exportDownloading: "جارِ تحضير الملف...",
    exportSuccess: "تم تحميل الملف بنجاح",
    exportFailed: "فشل تحميل الملف",
    // Missions
    missionsTitle: "المهمات الميدانية",
    missionsDesc: "إدارة المهمات والزيارات الميدانية",
    createMission: "إنشاء مهمة",
    totalMissions: "إجمالي المهمات",
    activeMissions: "قيد التنفيذ",
    completedMissions: "مكتملة",
    pendingMissionRequests: "طلبات معلقة",
    // Feedback Dashboard
    feedbackDashboard: "لوحة النتائج",
    totalFeedbacks: "إجمالي النتائج",
    veryInterested: "مهتم جداً",
    interested: "مهتم",
    contractsSigned: "عقود موقعة",
    needsFollowup: "يحتاج متابعة",
    totalDealValue: "إجمالي قيمة الصفقات",
    upcomingFollowups: "متابعات قادمة",
    recentFeedbacks: "أحدث النتائج",
    // Tabs
    tabAllMissions: "كل المهمات",
    tabPendingRequests: "طلبات معلقة",
    // Table
    missionTitle: "عنوان المهمة",
    missionEmployee: "الموظف",
    missionDate: "التاريخ",
    missionLocation: "الموقع",
    missionStatusCol: "الحالة",
    missionFeedback: "النتيجة",
    // Statuses
    missionStatusPending: "معلقة",
    missionStatusAssigned: "معينة",
    missionStatusActive: "قيد التنفيذ",
    missionStatusCompleted: "مكتملة",
    missionStatusCancelled: "ملغية",
    noMissionsData: "لا يوجد مهمات",
    noPendingRequests: "لا يوجد طلبات معلقة",
    // Live Locations
    locationsTitle: "المواقع الحية",
    locationsDesc: "متابعة موظفي الميدان لحظياً",
    trackedEmployees: "موظفون متتبعون",
    lastUpdate: "آخر تحديث",
    liveStatus: "الحالة",
    liveActive: "نشط",
    liveOffline: "غير متصل",
    autoRefresh: "تحديث تلقائي",
    refreshNow: "تحديث الآن",
    noLocationsData: "لا يوجد موظفون متتبعون حالياً",
    selectEmployee: "اختر موظف من القائمة",
    lat: "خط العرض",
    lng: "خط الطول",
    lastSeen: "آخر ظهور",
    justNow: "الآن",
    minutesAgo: "منذ دقائق",
    hoursAgo: "منذ ساعات",
    viewOnMap: "عرض على الخريطة",
    centerMap: "توسيط الخريطة",
    // Announcements
    announcementsTitle: "الإعلانات",
    announcementsDesc: "إدارة الإعلانات والإشعارات للموظفين",
    createAnnouncement: "إعلان جديد",
    totalAnnouncements: "إجمالي الإعلانات",
    unreadAnnouncements: "غير مقروءة",
    todayAnnouncements: "اليوم",
    announcementTitle: "العنوان",
    announcementContent: "المحتوى",
    announcementAuthor: "المرسل",
    announcementDate: "التاريخ",
    announcementPriority: "الأولوية",
    priorityHigh: "عالية",
    priorityMedium: "متوسطة",
    priorityLow: "منخفضة",
    isRead: "مقروء",
    isUnread: "غير مقروء",
    noAnnouncementsData: "لا يوجد إعلانات",
    createFirstAnnouncement: "إنشاء أول إعلان",
    filterAllAnn: "الكل",
    filterUnread: "غير مقروء",
    filterRead: "مقروء",
    dialogNewAnnouncement: "إنشاء إعلان جديد",
    dialogNewAnnouncementDesc: "أرسل إعلان لجميع الموظفين",
    annTitleLabel: "العنوان *",
    annContentLabel: "المحتوى *",
    annPriorityLabel: "الأولوية",
    publishAnnouncement: "نشر",
    annTitleRequired: "العنوان مطلوب",
    annContentRequired: "المحتوى مطلوب",
    annCreated: "تم النشر بنجاح",
    annCreateFailed: "فشل النشر",
    // Company Settings
    companyTitle: "إعدادات الشركة",
    companyDesc: "إدارة بيانات الشركة والإعدادات",
    tabCompanyInfo: "بيانات الشركة",
    tabStats: "إحصائيات",
    tabPayrollSettings: "إعدادات الرواتب",
    companyLogo: "شعار الشركة",
    uploadLogo: "رفع شعار",
    changeLogo: "تغيير الشعار",
    companyNameAr: "الاسم بالعربي",
    companyNameEn: "الاسم بالإنجليزي",
    companyPhone: "الهاتف",
    companyEmail: "البريد الإلكتروني",
    companyWebsite: "الموقع الإلكتروني",
    companyAddress: "العنوان",
    commercialRegister: "السجل التجاري",
    taxNumber: "الرقم الضريبي",
    industry: "النشاط",
    foundedDate: "تاريخ التأسيس",
    saveChanges: "حفظ التغييرات",
    branchesCount: "الفروع",
    departmentsCount: "الأقسام",
    employeesTotal: "الموظفون",
    // Payroll Settings
    lateDeductionRate: "خصم التأخير (لكل دقيقة)",
    absenceDeductionDay: "خصم الغياب (لكل يوم)",
    overtimeRate: "معدل الإضافي (لكل ساعة)",
    insuranceMode: "طريقة التأمين",
    insuranceModeNone: "لا يوجد",
    insuranceModeFixed: "مبلغ ثابت",
    insuranceModePercent: "نسبة مئوية",
    insuranceFixedAmount: "قيمة التأمين الثابتة",
    insurancePercent: "نسبة التأمين (%)",
    fieldAllowanceType: "بدل الميداني",
    fieldAllowanceNone: "بدون",
    fieldAllowanceFixed: "ثابت شهرياً",
    fieldAllowancePerVisit: "لكل زيارة",
    fixedFieldAllowance: "البدل الثابت",
    perVisitAllowance: "بدل الزيارة",
    payrollCycle: "دورة الرواتب",
    payrollCutoffDay: "يوم القطع",
    payrollPayDay: "يوم الصرف",
    cycleCalendarMonth: "شهر ميلادي",
    cycleCustom: "مخصص",
    egpUnit: "جنيه",
    settingsSaved: "تم الحفظ بنجاح",
    settingsSaveFailed: "فشل الحفظ",
    // Settings
    settingsTitle: "الإعدادات",
    settingsDesc: "إدارة حسابك وتفضيلاتك",
    tabProfileSettings: "الملف الشخصي",
    tabSecurity: "الأمان",
    tabPreferences: "التفضيلات",
    // Profile
    profileInfo: "بيانات الحساب",
    editProfile: "تعديل البيانات",
    // Security
    changePasswordTitle: "تغيير كلمة المرور",
    changePasswordDesc: "استخدم كلمة مرور قوية لحماية حسابك",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    passwordRequirements: "يجب أن تحتوي على 8 أحرف على الأقل",
    passwordMismatch: "كلمة المرور غير متطابقة",
    passwordTooShort: "كلمة المرور قصيرة جداً",
    passwordChanged: "تم تغيير كلمة المرور بنجاح",
    passwordChangeFailed: "فشل تغيير كلمة المرور",
    updatePassword: "تحديث كلمة المرور",
    // Preferences
    preferencesTitle: "التفضيلات",
    preferencesDesc: "اضبط تفضيلات النظام والإشعارات",
    languagePref: "اللغة",
    languageAr: "العربية",
    languageEn: "English",
    themePref: "المظهر",
    themeLight: "فاتح",
    themeDark: "داكن",
    themeSystem: "تلقائي",
    notificationsPref: "الإشعارات",
    emailNotifications: "إشعارات البريد",
    emailNotificationsDesc: "استقبال الإشعارات على البريد الإلكتروني",
    pushNotifications: "إشعارات التطبيق",
    pushNotificationsDesc: "استقبال إشعارات فورية في المتصفح",
    dailyReports: "التقارير اليومية",
    dailyReportsDesc: "استقبال ملخص يومي بالحضور والانصراف",
    weeklyReports: "التقارير الأسبوعية",
    weeklyReportsDesc: "استقبال ملخص أسبوعي شامل",
    prefsSaved: "تم حفظ التفضيلات",
    // Manager Dashboard
    managerDashboardTitle: "لوحة المدير",
    managerWelcome: "أهلاً بك",
    teamSize: "حجم الفريق",
    teamMembers: "أفراد الفريق",
    myTeamTitle: "فريقي",
    myTeamDesc: "الموظفون التابعون لك",
    quickStats: "إحصائيات سريعة",
    quickActionsManager: "إجراءات سريعة",
    viewTeam: "عرض الفريق",
    reviewRequests: "مراجعة الطلبات",
    trackTeam: "متابعة الفريق",
    createMissionMgr: "إنشاء مهمة",
    // Employee Dashboard
    empDashboardWelcome: "أهلاً بك",
    empDashboardDesc: "ملخص يومك ومهامك",
    checkInStatus: "حالة الحضور",
    notCheckedIn: "لم تسجل حضورك",
    checkedIn: "مسجل حضور",
    checkInNow: "تسجيل الحضور",
    checkOutNow: "تسجيل الانصراف",
    myShift: "شيفتي",
    shiftStart: "بداية الشيفت",
    shiftEnd: "نهاية الشيفت",
    hoursWorked: "الساعات المنجزة",
    myBalances: "أرصدتي",
    annualBalance: "الإجازة السنوية",
    sickBalance: "الإجازة المرضية",
    emergencyBalance: "الإجازة الطارئة",
    daysRemainingUnit: "يوم متبقي",
    myUpcoming: "القادم لي",
    upcomingLeaves: "إجازاتي القادمة",
    upcomingMissions: "مهماتي القادمة",
    noUpcomingLeaves: "لا يوجد إجازات قادمة",
    noUpcomingMissions: "لا يوجد مهمات قادمة",
    quickActionsEmp: "إجراءات سريعة",
    requestLeave: "طلب إجازة",
    submitRequest: "تقديم طلب",
    viewPayslipMy: "عرض كشف المرتب",
    viewProfileMy: "بياناتي",
    // Permissions Management
    permissionsTitle: "الصلاحيات",
    permissionsDesc: "إدارة الأدوار والصلاحيات للمستخدمين",
    tabRoles: "الأدوار",
    tabUsers: "المستخدمون",
    tabPermsRef: "قائمة الصلاحيات",
    totalRoles: "إجمالي الأدوار",
    totalUsers: "إجمالي المستخدمين",
    totalPerms: "إجمالي الصلاحيات",
    createRole: "إنشاء دور جديد",
    roleName: "اسم الدور",
    rolePermissions: "الصلاحيات",
    noRolesData: "لا يوجد أدوار",
    createFirstRole: "إنشاء أول دور",
    assignRole: "تعيين دور",
    userRole: "الدور",
    assignedRoles: "الأدوار المعينة",
    noAssignedRoles: "لا يوجد أدوار",
    permissionCode: "الكود",
    permissionLabel: "الوصف",
    searchPerms: "بحث في الصلاحيات...",
    // Policies Center
    policiesTitle: "مركز السياسات",
    policiesDesc: "إدارة سياسات الشركة والحضور والرواتب",
    totalPolicies: "إجمالي السياسات",
    activePolicies: "السياسات النشطة",
    // Policy Types
    attendancePoliciesTitle: "سياسات الحضور",
    attendancePoliciesDesc: "قواعد التأخير والغياب والإذونات",
    leavePoliciesTitle: "سياسات الإجازات",
    leavePoliciesDesc: "أنواع الإجازات وقواعدها",
    workPolicyTitle: "سياسة العمل الأسبوعي",
    workPolicyDesc: "أيام العمل والعطلات الأسبوعية",
    allowancePoliciesTitle: "سياسات البدلات",
    allowancePoliciesDesc: "بدل نقل، سكن، غذاء، إلخ",
    deductionPoliciesTitle: "سياسات الخصومات",
    deductionPoliciesDesc: "خصومات التأمين، القروض، إلخ",
    bonusPoliciesTitle: "سياسات المكافآت",
    bonusPoliciesDesc: "مكافآت الأداء والحوافز",
    // Actions
    manageThis: "إدارة",
    createPolicy: "إنشاء سياسة",
    activeCount: "نشطة",
    // Attendance Policy Detail
    policyName: "اسم السياسة",
    effectiveFrom: "ساري من",
    effectiveTo: "ساري إلى",
    policyStatus: "الحالة",
    permissionEnabled: "الأذونات مفعلة",
    monthlyPermHours: "ساعات الأذونات شهرياً",
    monthlyPermCount: "عدد الأذونات شهرياً",
    lateRules: "قواعد التأخير",
    absenceRules: "قواعد الغياب",
    overtimeRules: "قواعد الإضافي",
    // Org Chart
    orgChartTitle: "الهيكل التنظيمي",
    orgChartDesc: "عرض الشجرة التنظيمية للشركة",
    // Termination
    terminationTitle: "إنهاء الخدمة",
    terminationDesc: "إدارة الموظفين المنتهية خدمتهم",
    offboardedEmployees: "موظفون منتهية خدمتهم",
    reactivate: "إعادة تفعيل",
    terminationDate: "تاريخ الإنهاء",
    terminationReason: "سبب الإنهاء",
    noOffboarded: "لا يوجد موظفين منتهية خدمتهم",
    // Work Locations
    workLocationsTitle: "مواقع العمل",
    workLocationsDesc: "إدارة مواقع العمل المعتمدة",
    addWorkLocation: "إضافة موقع",
    workLocationName: "اسم الموقع",
    workLocationType: "نوع الموقع",
    workLocationAddress: "العنوان",
    workLocationRadius: "نطاق التغطية (متر)",
    noWorkLocations: "لا يوجد مواقع عمل",
    // Geofence
    geofenceTitle: "نطاق الجيو",
    geofenceDesc: "إعدادات النطاق الجغرافي للحضور",
    geofenceEnabled: "النطاق مفعل",
    geofenceLat: "خط العرض",
    geofenceLng: "خط الطول",
    geofenceRadius: "نصف القطر (متر)",
    geofenceAddress: "العنوان",
    updateGeofence: "تحديث النطاق",
    // Leave Recall
    leaveRecallTitle: "استدعاء الإجازات",
    leaveRecallDesc: "استدعاء الموظفين من إجازاتهم",
    recallEmployee: "استدعاء موظف",
    noRecalls: "لا يوجد استدعاءات",
    // Company Policies
    companyPoliciesTitle: "سياسات وملفات الشركة",
    companyPoliciesDesc: "لائحة النظام الداخلي والقواعد العامة",
    uploadPolicyFile: "رفع ملف",
    // Flex Shift
    flexShiftTitle: "تسويات الشيفت المرن",
    flexShiftDesc: "تسويات ساعات العمل للشيفت المرن",
    noFlexSettlements: "لا يوجد تسويات",
    // Footer
    designedBy: "Designed by",
    designedByName: "Eng/John Samir | JS Solutions",
  },
  en: {
    // Landing Page
    landingNav1: "Why MotionHR?",
    landingNav2: "Features",
    landingNav3: "Demo",
    landingNav4: "Contact",
    landingNavDemo: "Try Demo",
    landingNavCTA: "Book a Demo",
    landingBadge: "One system connecting daily operations, payroll & management",
    landingH1a: "From employee check-in",
    landingH1b: "to net salary",
    landingH1c: "your entire company runs in one place",
    landingSubtitle: "MotionHR is not just an HR system. It's a real operations platform: attendance, requests, leaves, missions, field teams, policies, payroll, and executive reports — all in one fast, clean experience.",
    landingCTA1: "Chat on WhatsApp",
    landingCTA2: "Try the Demo",
    landingCheck1: "Attendance + GPS + Field Teams",
    landingCheck2: "Payroll + Allowances + Deductions",
    landingCheck3: "Manager & HR Approvals",
    landingCheck4: "Excel / PDF Export",
    landingPainTitle: "If you have any of these problems,",
    landingPainTitleAccent: "MotionHR is built for you",
    landingPainSubtitle: "We solve the gap between daily operations, manager visibility, and HR control over payroll and reporting.",
    landingFeaturesTitle: "Everything you need to run daily operations",
    landingFeaturesSubtitle: "From employee check-in to payroll export — no detours.",
    landingPortalsTitle: "3 Portals in one system",
    landingPortalsSubtitle: "Every role has a tailored experience: employee, manager, and HR.",
    landingWorkflowTitle: "From day one to end of month",
    landingWorkflowSubtitle: "MotionHR connects your real company operations in one clear flow: daily tracking, faster decisions, and salaries calculated on actual data.",
    landingDemoTitle: "Want to see MotionHR in action? Try it or contact us now",
    landingDemoSubtitle: "You can explore the interface yourself, or message us on WhatsApp and we'll arrange a live demo tailored to your company.",
    landingDemo1Title: "Try the Demo",
    landingDemo1Desc: "Access the system and explore the main flows: attendance, requests, org chart, and reports.",
    landingDemo1Btn: "Try Now",
    landingDemo2Title: "Live Demo with Developer",
    landingDemo2Desc: "Want a walkthrough tailored to your business? Message us on WhatsApp directly.",
    landingDemo2Btn: "Book WhatsApp Demo",
    landingContactTitle: "Ready to see MotionHR on your company?",
    landingContactSubtitle: "Fastest way: send a WhatsApp message, email us, or jump into the demo.",
    landingWA: "WhatsApp Direct",
    landingWADesc: "Fastest channel for quick answers or booking a demo.",
    landingMail: "Email Us",
    landingMailDesc: "Ideal for sending company details or formal requests.",
    landingDemoCard: "Try the System",
    landingDemoCardDesc: "Enter the demo and experience the system yourself.",
    landingFloatingWA: "WhatsApp Us",
    landingDemoReady: "Demo Ready",
    landingFooter: "Designed & Developed by",
    // Sidebar
    dashboard: "Dashboard",
    employees: "Employees",
    attendance: "Attendance",
    leaves: "Leaves",
    requests: "Requests",
    payroll: "Payroll",
    payrollRuns: "Payroll Runs",
    manualEntries: "Manual Entries",
    missions: "Missions",
    locations: "Live Locations",
    announcements: "Announcements",
    departments: "Departments",
    branches: "Branches",
    shifts: "Shifts",
    jobTitles: "Job Titles",
    company: "Company",
    settings: "Settings",
    trustedDevices: "Trusted Devices",
    importEmployees: "Import Employees",
    myTeam: "My Team",
    myAttendance: "My Attendance",
    myLeaves: "My Leaves",
    myRequests: "My Requests",
    myMissions: "My Missions",
    myPayslip: "My Payslip",
    myProfile: "My Profile",
    myPermissions: "My Permissions",
    myFieldVisits: "Field Visits",
    notifications: "Notifications",
    companyRegulations: "Company Regulations & Charter",
    reports: "Reports",
    // Header
    logout: "Logout",
    profile: "Profile",
    search: "Quick search...",
    // Dashboard
    totalEmployees: "Total Employees",
    presentToday: "Present Today",
    onLeave: "On Leave",
    pendingRequests: "Pending Requests",
    comingSoon: "Coming Soon",
    activeEmployees: "Active Employees",
    quickActions: "Quick Actions",
    recentActivity: "Recent Activity",
    noActivity: "No activity yet",
    noActivityDesc: "Activity log will appear here soon",
    welcome: "Welcome",
    overview: "Overview of",
    // Shared
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving...",
    create: "Create",
    noResults: "No results found",
    active: "Active",
    inactive: "Inactive",
    employee_count: "employees",
    average: "Average",
    total: "Total",
    // Departments
    addDepartment: "Add Department",
    departmentsTitle: "Departments",
    departmentsDesc: "Manage company departments",
    totalDepartments: "Total Departments",
    avgEmployeesPerDept: "Avg Employees/Dept",
    searchDepartments: "Search departments...",
    noDepartments: "No departments yet",
    addFirstDept: "Add First Department",
    addDeptTitle: "Add New Department",
    addDeptDesc: "Enter department details",
    deptNameAr: "Arabic Name *",
    deptNameEn: "English Name",
    deptDesc: "Description",
    deptDescPlaceholder: "Brief description...",
    createDept: "Create Department",
    failedLoad: "Failed to load data",
    failedCreate: "Failed to create department",
    createdSuccess: "Department created successfully",
    nameArRequired: "Arabic name is required",
    // Branches
    addBranch: "Add Branch",
    branchesTitle: "Branches",
    branchesDesc: "Manage company branches",
    totalBranches: "Total Branches",
    avgEmployeesPerBranch: "Avg Employees/Branch",
    searchBranches: "Search branches...",
    noBranches: "No branches yet",
    addFirstBranch: "Add First Branch",
    addBranchTitle: "Add New Branch",
    addBranchDesc: "Enter branch details",
    branchNameAr: "Arabic Name *",
    branchNameEn: "English Name",
    branchAddress: "Address",
    branchPhone: "Phone Number",
    createBranch: "Create Branch",
    mainBranch: "Main Branch",
    failedCreateBranch: "Failed to create branch",
    createdBranchSuccess: "Branch created successfully",
    branchNameArRequired: "Arabic branch name is required",
    // Shifts
    addShift: "Add Shift",
    shiftsTitle: "Shifts",
    shiftsDesc: "Manage work shifts",
    totalShifts: "Total Shifts",
    defaultShift: "Default Shift",
    activeShifts: "Active",
    searchShifts: "Search shifts...",
    noShifts: "No shifts yet",
    addFirstShift: "Add First Shift",
    shiftFixed: "Fixed",
    shiftFlex: "Flexible",
    shiftOpen: "Open",
    shiftStart: "Start",
    shiftEnd: "End",
    shiftHours: "Hours",
    shiftGrace: "Grace",
    shiftBreak: "Break",
    shiftMin: "min",
    assignEmployees: "Assign Employees",
    failedCreateShift: "Failed to create shift",
    createdShiftSuccess: "Shift created successfully",
    shiftNameRequired: "Shift name is required",
    // Job Titles
    addJobTitle: "Add Job Title",
    jobTitlesTitle: "Job Titles",
    jobTitlesDesc: "Manage positions and roles",
    totalJobTitles: "Total Job Titles",
    avgEmployeesPerTitle: "Avg Employees/Title",
    searchJobTitles: "Search job titles...",
    noJobTitles: "No job titles yet",
    addFirstJobTitle: "Add First Job Title",
    addJobTitleDialog: "Add Job Title",
    addJobTitleDesc: "Enter job title details",
    jobTitleNameAr: "Arabic Name *",
    jobTitleNameEn: "English Name",
    jobTitleDescLabel: "Description",
    createJobTitle: "Create",
    failedCreateTitle: "Failed to create",
    createdTitleSuccess: "Job title created successfully",
    titleNameArRequired: "Arabic name is required",
    // Employees List
    employeesTitle: "Employees",
    employeesDesc: "Manage all company employees",
    activeEmployeesCount: "Active",
    inactiveEmployees: "Inactive",
    importBtn: "Import",
    addEmployee: "Add Employee",
    searchEmployees: "Search by name, code, phone, national ID...",
    allDepts: "All Departments",
    allStatuses: "All Statuses",
    statusActive: "Active",
    statusInactive: "Inactive",
    statusOnLeave: "On Leave",
    statusTerminated: "Terminated",
    statusResigned: "Resigned",
    colEmployee: "Employee",
    colCode: "Code",
    colDept: "Department",
    colJobTitle: "Job Title",
    colBranch: "Branch",
    colPhone: "Phone",
    colStatus: "Status",
    noEmployees: "No employees found",
    failedLoadEmployees: "Failed to load employees",
    showingOf: "Showing",
    of: "of",
    ofTotal: "of total",
    deptFilter: "Department",
    statusFilter: "Status",
    // Employee Detail
    employeeNotFound: "Employee not found",
    backToList: "Back to list",
    backToEmployees: "Back to employees",
    personalInfo: "Personal Info",
    jobInfo: "Job Info",
    salaryInfo: "Salary",
    contractInfo: "Contract",
    nameAr: "Arabic Name",
    nameEn: "English Name",
    nationalId: "National ID",
    birthDate: "Date of Birth",
    gender: "Gender",
    maritalStatus: "Marital Status",
    religion: "Religion",
    nationality: "Nationality",
    contactInfo: "Contact",
    phone: "Phone",
    phone2: "Secondary Phone",
    email: "Email",
    city: "City",
    addressField: "Address",
    empCode: "Employee Code",
    hireDate: "Hire Date",
    dept: "Department",
    branch: "Branch",
    jobTitle: "Job Title",
    directManager: "Direct Manager",
    attendancePattern: "Attendance Pattern",
    workerType: "Worker Type",
    empStatus: "Employment Status",
    basicSalary: "Basic Salary",
    currency: "Currency",
    bankName: "Bank",
    bankAccount: "Account Number",
    iban: "IBAN",
    contractType: "Contract Type",
    contractStart: "Contract Start",
    contractEnd: "Contract End",
    // Import Page
    importTitle: "Import Employees",
    importDesc: "Upload an Excel file to add or update employees in bulk",
    uploadFile: "Upload File",
    downloadTemplate: "Download Template",
    dragDrop: "Drag and drop file here",
    orClick: "or click to browse",
    maxSize: "Max 10 MB",
    startImport: "Start Import",
    uploading: "Uploading...",
    importSuccess: "Import successful",
    importFailed: "Import failed",
    newEmployees: "new employees",
    updatedEmployees: "updated",
    errors: "errors",
    errorDetails: "Error Details",
    row: "Row",
    selectExcel: "Please select an Excel file (.xlsx or .xls)",
    fileTooLarge: "File too large (max 10 MB)",
    templateDownloaded: "Template downloaded successfully",
    templateFailed: "Failed to download template",
    serverError: "Server connection error",
    upTo500: "Up to 500 employees",
    perBatch: "per batch",
    fields67: "67 fields",
    comprehensiveData: "Comprehensive data per employee",
    autoValidation: "Auto validation",
    validationDesc: "Data validated before saving",
    kb: "KB",
    importInstructions: "Import Instructions",
    step1: "Download Template",
    step1Desc: "Click download template to get the sheet",
    step2: "Fill Data",
    step2Desc: "Enter employee data in the sheet",
    step3: "Upload File",
    step3Desc: "Upload the completed file here",
    importNotes: "Notes",
    note1: "Fields marked * are required",
    note2: "National ID must be 14 digits",
    note3: "Dates in YYYY-MM-DD format",
    note4: "Phone in 01XXXXXXXXX format",
    // Payroll
    payrollTitle: "Payroll",
    payrollDesc: "Manage employee payroll",
    selectMonth: "Month",
    selectYear: "Year",
    grandTotalSalary: "Total Salaries",
    grandTotalAllowances: "Total Allowances",
    grandTotalOvertime: "Total Overtime",
    grandTotalBonuses: "Total Bonuses",
    grandTotalDeductions: "Total Deductions",
    grandTotalNet: "Net Payable",
    empName: "Employee Name",
    basicSalaryCol: "Basic",
    allowancesCol: "Allowances",
    bonusesCol: "Bonuses",
    overtimeCol: "Overtime",
    deductionsCol: "Deductions",
    netSalaryCol: "Net",
    searchPayroll: "Search by name or code...",
    noPayrollData: "No payroll data for this month",
    workingDays: "Working Days",
    presentDays: "Present Days",
    absentDays: "Absent Days",
    lateMinutes: "Late Minutes",
    overtimeHours: "Overtime Hours",
    onLeaveDays: "Leave Days",
    missionDays: "Mission Days",
    exportExcel: "Export Excel",
    exportPDF: "Export PDF",
    viewPayslip: "View Payslip",
    payslipTitle: "Payslip",
    forEmployee: "For",
    forMonth: "For Month",
    salaryBreakdown: "Salary Breakdown",
    attendanceSummary: "Attendance Summary",
    deductionsBreakdown: "Deductions Breakdown",
    lateDeduction: "Late Deduction",
    absenceDeduction: "Absence Deduction",
    earlyLeaveDeduction: "Early Leave Deduction",
    insuranceDeduction: "Insurance",
    installments: "Installments",
    penalties: "Penalties",
    extraDeductions: "Extra Deductions",
    nightAllowance: "Night Allowance",
    weekendAllowance: "Weekend Allowance",
    fieldAllowance: "Field Allowance",
    grossSalary: "Gross Salary",
    monthlyComparison: "Monthly Comparison",
    monthlyComparisonDesc: "Compare payroll between months",
    advancedFilters: "Advanced Filters",
    filterByBranch: "Filter by Branch",
    filterByDept: "Filter by Department",
    payrollAnalytics: "Payroll Analytics",
    salaryDistribution: "Salary Distribution",
    topPaid: "Top Paid",
    payrollTrends: "Payroll Trends",
    bulkPayment: "Bulk Payment",
    processPayment: "Process Payment",
    January: "January",
    February: "February",
    March: "March",
    April: "April",
    May: "May",
    June: "June",
    July: "July",
    August: "August",
    September: "September",
    October: "October",
    November: "November",
    December: "December",
    // Attendance
    attendanceTitle: "Attendance",
    attendanceDesc: "Track employee attendance",
    selectDate: "Select Date",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    thisMonth: "This Month",
    statusPresent: "Present",
    statusLate: "Late",
    statusAbsent: "Absent",
    statusOnLeaveAtt: "On Leave",
    statusWeekend: "Weekend",
    statusMission: "Mission",
    statusNoData: "No Data",
    checkIn: "Check In",
    checkOut: "Check Out",
    workHours: "Work Hours",
    lateMinutesCol: "Late Minutes",
    earlyLeaveMinutes: "Early Leave Minutes",
    overtimeHoursCol: "Overtime Hours",
    shiftName: "Shift",
    nightShift: "Night Shift",
    weekendWork: "Weekend Work",
    filterByStatus: "Filter by Status",
    allStatusesAtt: "All Statuses",
    monthlyReport: "Monthly Report",
    dailyReport: "Daily Report",
    noAttendanceData: "No attendance data for this day",
    totalPresent: "Total Present",
    totalLate: "Total Late",
    totalAbsent: "Total Absent",
    totalOnLeave: "Total On Leave",
    totalWeekend: "Weekend",
    totalMission: "On Mission",
    exportAttendance: "Export Attendance",
    // Leaves
    leavesTitle: "Leaves",
    leavesDesc: "Track employee leaves and balances",
    totalLeaves: "Total Leaves",
    approvedLeaves: "Approved",
    pendingLeaves: "Pending",
    rejectedLeaves: "Rejected",
    leaveTypesTitle: "Leave Types",
    leaveTypeName: "Leave Type",
    daysAllowed: "Total Balance",
    daysUsed: "Used",
    daysPending: "Pending",
    daysRemaining: "Remaining",
    balancesTitle: "Employee Balances",
    colBalance: "Balance",
    colUsed: "Used",
    colRemaining: "Remaining",
    colUnpaid: "Unpaid",
    colHalfDay: "Half Day",
    noLeavesData: "No leaves data",
    leaveCategoryAnnual: "Annual",
    leaveCategorySick: "Sick",
    leaveCategoryEmergency: "Emergency",
    leaveCategoryUnpaid: "Unpaid",
    leaveCategoryMaternity: "Maternity",
    leaveCategoryOther: "Other",
    daysUnit: "days",
    viewLeaveDetails: "View Details",
    addLeave: "Add Leave",
    leaveStatus: "Status",
    leaveApproved: "Approved",
    leavePending: "Pending",
    leaveRejected: "Rejected",
    leaveType: "Type",
    leaveDates: "Dates",
    leaveReason: "Reason",
    // Requests
    requestsTitle: "Requests",
    requestsDesc: "Track employee requests and approvals",
    totalRequests: "Total Requests",
    approvedRequests: "Approved",
    pendingRequestsCount: "Pending",
    rejectedRequests: "Rejected",
    requestCategories: "Request Categories",
    requestTypes: "Request Types",
    tabAllRequests: "All Requests",
    tabPendingOnly: "Pending Only",
    requestType: "Request Type",
    requestDate: "Request Date",
    requestStatus: "Status",
    requestActions: "Actions",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    viewDetails: "Details",
    reqApproved: "Approved",
    reqPending: "Pending",
    reqRejected: "Rejected",
    reqCancelled: "Cancelled",
    noRequestsData: "No requests found",
    typesInCategory: "types",
    requestReason: "Reason",
    requestAmount: "Amount",
    requestFrom: "From",
    requestTo: "To",
    submittedBy: "Submitted by",
    submittedAt: "Submitted at",
    // Reports
    reportsTitle: "Reports",
    reportsDesc: "Comprehensive reports on employees, attendance and payroll",
    reportsCategoryAttendance: "Attendance Reports",
    reportsCategoryLeaves: "Leaves Reports",
    reportsCategoryPayroll: "Payroll Reports",
    reportsCategoryOther: "Other Reports",
    // Individual Reports
    reportDailyAttendance: "Daily Attendance",
    reportDailyAttendanceDesc: "Track employee attendance daily",
    reportMonthlyAttendance: "Monthly Attendance",
    reportMonthlyAttendanceDesc: "Monthly attendance summary per employee",
    reportLate: "Late Arrivals",
    reportLateDesc: "Late employees and duration",
    reportAbsence: "Absence",
    reportAbsenceDesc: "Absent days per employee",
    reportLeaves: "Leaves",
    reportLeavesDesc: "Basic leaves report",
    reportLeavesEnhanced: "Leaves (Detailed)",
    reportLeavesEnhancedDesc: "Comprehensive report with balances",
    reportWorkHours: "Work Hours",
    reportWorkHoursDesc: "Actual and overtime work hours",
    reportRequests: "Requests",
    reportRequestsDesc: "Employee requests and status",
    reportPayrollAll: "Payroll",
    reportPayrollAllDesc: "Monthly payroll report",
    reportPermissions: "Permissions",
    reportPermissionsDesc: "Late and early leave permissions",
    reportShifts: "Shifts",
    reportShiftsDesc: "Employee distribution on shifts",
    reportExports: "Export",
    reportExportsDesc: "Export reports as PDF and Excel",
    openReport: "Open Report",
    comingSoonReport: "Coming Soon",
    // Absence Report
    absenceReportTitle: "Absence Report",
    absenceReportDesc: "Monthly absence details for employees",
    backToReports: "Back to Reports",
    totalWorkingDaysInMonth: "Working Days in Month",
    totalEmployeesWithAbsence: "Employees with Absence",
    totalAbsenceDays: "Total Absence Days",
    absenceRate: "Absence Rate",
    colAttendedDays: "Attended Days",
    colAbsentDays: "Absent Days",
    colAbsentDates: "Absent Dates",
    viewAllDates: "View All Dates",
    hideAllDates: "Hide Dates",
    period: "Period",
    noAbsenceData: "No absence data",
    absenceRateHigh: "High Absence",
    absenceRateMedium: "Medium Absence",
    absenceRateLow: "Low Absence",
    // Late Report
    lateReportTitle: "Late Arrivals Report",
    lateReportDesc: "Monthly late arrivals details for employees",
    totalEmployeesWithLate: "Employees with Late",
    totalLateDays: "Total Late Days",
    totalLateMinutesReport: "Total Late Minutes",
    avgLateMinutes: "Average Late Minutes",
    colLateDays: "Late Days",
    colLateMinutes: "Late Minutes",
    colAvgLate: "Avg Late/Day",
    colLateDates: "Late Dates",
    noLateData: "No late data",
    lateSeverityHigh: "High Delay",
    lateSeverityMedium: "Medium Delay",
    lateSeverityLow: "Low Delay",
    minutes: "min",
    // Work Hours Report
    workHoursReportTitle: "Work Hours Report",
    workHoursReportDesc: "Total actual work hours per employee",
    totalHoursMonth: "Total Hours",
    totalDaysWorked: "Days Worked",
    avgHoursPerDay: "Avg Hours/Day",
    colTotalHours: "Total Hours",
    colDaysWorked: "Days",
    colAvgHours: "Avg/Day",
    colDailyBreakdown: "Daily Breakdown",
    noWorkHoursData: "No work hours data",
    hoursUnit: "hrs",
    productivity: "Productivity",
    productivityHigh: "High Productivity",
    productivityMedium: "Medium Productivity",
    productivityLow: "Low Productivity",
    // Permissions Report
    permissionsReportTitle: "Permissions Report",
    permissionsReportDesc: "Late arrival and early leave permissions",
    maxHoursPerMonth: "Monthly Max Hours",
    maxTimesPerMonth: "Allowed Times",
    usedHours: "Used Hours",
    usedTimes: "Used Times",
    remainingHours: "Remaining Hours",
    colMaxHours: "Max Hours",
    colUsedMinutes: "Used (min)",
    colUsedHours: "Used (hrs)",
    colMovementsCount: "Movements",
    colMovements: "Details",
    noPermissionsData: "No permissions data",
    permissionMovement: "movement",
    movements_word: "movements",
    percentageUsed: "Usage %",
    usageHigh: "High Usage",
    usageMedium: "Medium Usage",
    usageLow: "Low Usage",
    // Monthly Attendance Report
    monthlyAttReportTitle: "Monthly Attendance Report",
    monthlyAttReportDesc: "Monthly attendance summary per employee",
    totalCheckins: "Total Check-ins",
    totalCheckouts: "Total Check-outs",
    totalMonthDays: "Month Days",
    colCheckins: "Check-ins",
    colCheckouts: "Check-outs",
    colWorkingDays: "Working Days",
    colMonthDays: "Month Days",
    colAttendanceRate: "Attendance Rate",
    noMonthlyAttData: "No monthly attendance data",
    attRateExcellent: "Excellent",
    attRateGood: "Good",
    attRateAverage: "Average",
    attRatePoor: "Poor",
    // Leaves Basic Report
    leavesBasicTitle: "Leaves Report",
    leavesBasicDesc: "Simple report of submitted leaves",
    startDate: "Start Date",
    endDate: "End Date",
    leaveDaysCount: "Days Count",
    colLeaveType: "Leave Type",
    colStartDate: "From",
    colEndDate: "To",
    colDaysCount: "Days",
    colLeaveStatus: "Status",
    filterAll: "All",
    // Export
    exportDownloading: "Preparing file...",
    exportSuccess: "File downloaded successfully",
    exportFailed: "Failed to download file",
    // Missions
    missionsTitle: "Field Missions",
    missionsDesc: "Manage field missions and visits",
    createMission: "Create Mission",
    totalMissions: "Total Missions",
    activeMissions: "Active",
    completedMissions: "Completed",
    pendingMissionRequests: "Pending Requests",
    // Feedback Dashboard
    feedbackDashboard: "Results Dashboard",
    totalFeedbacks: "Total Feedbacks",
    veryInterested: "Very Interested",
    interested: "Interested",
    contractsSigned: "Contracts Signed",
    needsFollowup: "Needs Followup",
    totalDealValue: "Total Deal Value",
    upcomingFollowups: "Upcoming Followups",
    recentFeedbacks: "Recent Feedbacks",
    // Tabs
    tabAllMissions: "All Missions",
    tabPendingRequests: "Pending Requests",
    // Table
    missionTitle: "Mission Title",
    missionEmployee: "Employee",
    missionDate: "Date",
    missionLocation: "Location",
    missionStatusCol: "Status",
    missionFeedback: "Result",
    // Statuses
    missionStatusPending: "Pending",
    missionStatusAssigned: "Assigned",
    missionStatusActive: "Active",
    missionStatusCompleted: "Completed",
    missionStatusCancelled: "Cancelled",
    noMissionsData: "No missions found",
    noPendingRequests: "No pending requests",
    // Live Locations
    locationsTitle: "Live Locations",
    locationsDesc: "Track field employees in real-time",
    trackedEmployees: "Tracked Employees",
    lastUpdate: "Last Update",
    liveStatus: "Status",
    liveActive: "Active",
    liveOffline: "Offline",
    autoRefresh: "Auto Refresh",
    refreshNow: "Refresh Now",
    noLocationsData: "No tracked employees currently",
    selectEmployee: "Select an employee from the list",
    lat: "Latitude",
    lng: "Longitude",
    lastSeen: "Last Seen",
    justNow: "Just now",
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",
    viewOnMap: "View on Map",
    centerMap: "Center Map",
    // Announcements
    announcementsTitle: "Announcements",
    announcementsDesc: "Manage announcements and notifications for employees",
    createAnnouncement: "New Announcement",
    totalAnnouncements: "Total Announcements",
    unreadAnnouncements: "Unread",
    todayAnnouncements: "Today",
    announcementTitle: "Title",
    announcementContent: "Content",
    announcementAuthor: "Sender",
    announcementDate: "Date",
    announcementPriority: "Priority",
    priorityHigh: "High",
    priorityMedium: "Medium",
    priorityLow: "Low",
    isRead: "Read",
    isUnread: "Unread",
    noAnnouncementsData: "No announcements",
    createFirstAnnouncement: "Create First Announcement",
    filterAllAnn: "All",
    filterUnread: "Unread",
    filterRead: "Read",
    dialogNewAnnouncement: "Create New Announcement",
    dialogNewAnnouncementDesc: "Send announcement to all employees",
    annTitleLabel: "Title *",
    annContentLabel: "Content *",
    annPriorityLabel: "Priority",
    publishAnnouncement: "Publish",
    annTitleRequired: "Title is required",
    annContentRequired: "Content is required",
    annCreated: "Published successfully",
    annCreateFailed: "Failed to publish",
    // Company Settings
    companyTitle: "Company Settings",
    companyDesc: "Manage company info and settings",
    tabCompanyInfo: "Company Info",
    tabStats: "Statistics",
    tabPayrollSettings: "Payroll Settings",
    companyLogo: "Company Logo",
    uploadLogo: "Upload Logo",
    changeLogo: "Change Logo",
    companyNameAr: "Arabic Name",
    companyNameEn: "English Name",
    companyPhone: "Phone",
    companyEmail: "Email",
    companyWebsite: "Website",
    companyAddress: "Address",
    commercialRegister: "Commercial Register",
    taxNumber: "Tax Number",
    industry: "Industry",
    foundedDate: "Founded Date",
    saveChanges: "Save Changes",
    branchesCount: "Branches",
    departmentsCount: "Departments",
    employeesTotal: "Employees",
    // Payroll Settings
    lateDeductionRate: "Late Deduction (per minute)",
    absenceDeductionDay: "Absence Deduction (per day)",
    overtimeRate: "Overtime Rate (per hour)",
    insuranceMode: "Insurance Mode",
    insuranceModeNone: "None",
    insuranceModeFixed: "Fixed Amount",
    insuranceModePercent: "Percentage",
    insuranceFixedAmount: "Fixed Insurance Amount",
    insurancePercent: "Insurance Percent (%)",
    fieldAllowanceType: "Field Allowance",
    fieldAllowanceNone: "None",
    fieldAllowanceFixed: "Monthly Fixed",
    fieldAllowancePerVisit: "Per Visit",
    fixedFieldAllowance: "Fixed Allowance",
    perVisitAllowance: "Per Visit Amount",
    payrollCycle: "Payroll Cycle",
    payrollCutoffDay: "Cutoff Day",
    payrollPayDay: "Pay Day",
    cycleCalendarMonth: "Calendar Month",
    cycleCustom: "Custom",
    egpUnit: "EGP",
    settingsSaved: "Saved successfully",
    settingsSaveFailed: "Failed to save",
    // Settings
    settingsTitle: "Settings",
    settingsDesc: "Manage your account and preferences",
    tabProfileSettings: "Profile",
    tabSecurity: "Security",
    tabPreferences: "Preferences",
    // Profile
    profileInfo: "Account Information",
    editProfile: "Edit Profile",
    // Security
    changePasswordTitle: "Change Password",
    changePasswordDesc: "Use a strong password to protect your account",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordRequirements: "Must contain at least 8 characters",
    passwordMismatch: "Passwords do not match",
    passwordTooShort: "Password too short",
    passwordChanged: "Password changed successfully",
    passwordChangeFailed: "Failed to change password",
    updatePassword: "Update Password",
    // Preferences
    preferencesTitle: "Preferences",
    preferencesDesc: "Configure system and notification preferences",
    languagePref: "Language",
    languageAr: "Arabic",
    languageEn: "English",
    themePref: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "Auto",
    notificationsPref: "Notifications",
    emailNotifications: "Email Notifications",
    emailNotificationsDesc: "Receive notifications by email",
    pushNotifications: "Push Notifications",
    pushNotificationsDesc: "Receive instant browser notifications",
    dailyReports: "Daily Reports",
    dailyReportsDesc: "Receive daily attendance summary",
    weeklyReports: "Weekly Reports",
    weeklyReportsDesc: "Receive comprehensive weekly summary",
    prefsSaved: "Preferences saved",
    // Manager Dashboard
    managerDashboardTitle: "Manager Dashboard",
    managerWelcome: "Welcome",
    teamSize: "Team Size",
    teamMembers: "Team Members",
    myTeamTitle: "My Team",
    myTeamDesc: "Employees reporting to you",
    quickStats: "Quick Stats",
    quickActionsManager: "Quick Actions",
    viewTeam: "View Team",
    reviewRequests: "Review Requests",
    trackTeam: "Track Team",
    createMissionMgr: "Create Mission",
    // Employee Dashboard
    empDashboardWelcome: "Welcome",
    empDashboardDesc: "Your day summary and tasks",
    checkInStatus: "Check-in Status",
    notCheckedIn: "Not checked in yet",
    checkedIn: "Checked in",
    checkInNow: "Check In Now",
    checkOutNow: "Check Out Now",
    myShift: "My Shift",
    shiftStart: "Shift Start",
    shiftEnd: "Shift End",
    hoursWorked: "Hours Worked",
    myBalances: "My Balances",
    annualBalance: "Annual Leave",
    sickBalance: "Sick Leave",
    emergencyBalance: "Emergency Leave",
    daysRemainingUnit: "days left",
    myUpcoming: "Upcoming",
    upcomingLeaves: "Upcoming Leaves",
    upcomingMissions: "Upcoming Missions",
    noUpcomingLeaves: "No upcoming leaves",
    noUpcomingMissions: "No upcoming missions",
    quickActionsEmp: "Quick Actions",
    requestLeave: "Request Leave",
    submitRequest: "Submit Request",
    viewPayslipMy: "View Payslip",
    viewProfileMy: "My Profile",
    // Permissions Management
    permissionsTitle: "Permissions",
    permissionsDesc: "Manage roles and permissions for users",
    tabRoles: "Roles",
    tabUsers: "Users",
    tabPermsRef: "Permissions List",
    totalRoles: "Total Roles",
    totalUsers: "Total Users",
    totalPerms: "Total Permissions",
    createRole: "Create New Role",
    roleName: "Role Name",
    rolePermissions: "Permissions",
    noRolesData: "No roles yet",
    createFirstRole: "Create First Role",
    assignRole: "Assign Role",
    userRole: "Role",
    assignedRoles: "Assigned Roles",
    noAssignedRoles: "No roles",
    permissionCode: "Code",
    permissionLabel: "Description",
    searchPerms: "Search permissions...",
    // Policies Center
    policiesTitle: "Policies Center",
    policiesDesc: "Manage company, attendance and payroll policies",
    totalPolicies: "Total Policies",
    activePolicies: "Active Policies",
    // Policy Types
    attendancePoliciesTitle: "Attendance Policies",
    attendancePoliciesDesc: "Late, absence and permission rules",
    leavePoliciesTitle: "Leave Policies",
    leavePoliciesDesc: "Leave types and rules",
    workPolicyTitle: "Weekly Work Policy",
    workPolicyDesc: "Work days and weekly holidays",
    allowancePoliciesTitle: "Allowance Policies",
    allowancePoliciesDesc: "Transport, housing, food, etc.",
    deductionPoliciesTitle: "Deduction Policies",
    deductionPoliciesDesc: "Insurance, loans, etc.",
    bonusPoliciesTitle: "Bonus Policies",
    bonusPoliciesDesc: "Performance bonuses and incentives",
    // Actions
    manageThis: "Manage",
    createPolicy: "Create Policy",
    activeCount: "active",
    // Attendance Policy Detail
    policyName: "Policy Name",
    effectiveFrom: "Effective From",
    effectiveTo: "Effective To",
    policyStatus: "Status",
    permissionEnabled: "Permissions Enabled",
    monthlyPermHours: "Monthly Permission Hours",
    monthlyPermCount: "Monthly Permission Count",
    lateRules: "Late Rules",
    absenceRules: "Absence Rules",
    overtimeRules: "Overtime Rules",
    // Org Chart
    orgChartTitle: "Organization Chart",
    orgChartDesc: "View company organizational tree",
    // Termination
    terminationTitle: "Termination",
    terminationDesc: "Manage terminated employees",
    offboardedEmployees: "Offboarded Employees",
    reactivate: "Reactivate",
    terminationDate: "Termination Date",
    terminationReason: "Termination Reason",
    noOffboarded: "No offboarded employees",
    // Work Locations
    workLocationsTitle: "Work Locations",
    workLocationsDesc: "Manage approved work locations",
    addWorkLocation: "Add Location",
    workLocationName: "Location Name",
    workLocationType: "Location Type",
    workLocationAddress: "Address",
    workLocationRadius: "Coverage Radius (meters)",
    noWorkLocations: "No work locations",
    // Geofence
    geofenceTitle: "Geofence",
    geofenceDesc: "Geographic boundary settings for attendance",
    geofenceEnabled: "Geofence Enabled",
    geofenceLat: "Latitude",
    geofenceLng: "Longitude",
    geofenceRadius: "Radius (meters)",
    geofenceAddress: "Address",
    updateGeofence: "Update Geofence",
    // Leave Recall
    leaveRecallTitle: "Leave Recall",
    leaveRecallDesc: "Recall employees from their leaves",
    recallEmployee: "Recall Employee",
    noRecalls: "No recalls",
    // Company Policies
    companyPoliciesTitle: "Company Policies & Files",
    companyPoliciesDesc: "Internal regulations and general rules",
    uploadPolicyFile: "Upload File",
    // Flex Shift
    flexShiftTitle: "Flex Shift Settlements",
    flexShiftDesc: "Working hours settlements for flex shift",
    noFlexSettlements: "No settlements",
    // Footer
    designedBy: "Designed by",
    designedByName: "Eng/John Samir | JS Solutions",
  },
} as const;

export type DictKey = keyof typeof dict.ar;

export function useDict() {
  const lang = useLangStore((s) => s.lang);
  return dict[lang];
}



