import { create } from "zustand";
import { persist } from "zustand/middleware";

type Lang = "ar" | "en";

interface LangState {
  lang: Lang;
  setLang: (lang: Lang) => void;
  isRTL: () => boolean;
}

export const useLangStore = create<LangState>()(
  persist(
    (set, get) => ({
      lang: "ar",
      setLang: (lang) => {
        set({ lang });
        if (typeof document !== "undefined") {
          document.documentElement.lang = lang;
          document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
        }
      },
      isRTL: () => get().lang === "ar",
    }),
    { name: "motionhr_language" }
  )
);

export const dict = {
  ar: {
    // Sidebar
    dashboard: "الرئيسية",
    employees: "الموظفون",
    attendance: "الحضور والانصراف",
    leaves: "الإجازات",
    requests: "الطلبات",
    payroll: "الرواتب",
    missions: "المهمات",
    locations: "المواقع المباشرة",
    announcements: "الإعلانات",
    departments: "الأقسام",
    branches: "الفروع",
    shifts: "الشيفتات",
    jobTitles: "المسميات الوظيفية",
    company: "الشركة",
    settings: "الإعدادات",
    importEmployees: "استيراد الموظفين",
    // Header
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    search: "بحث سريع...",
    // Dashboard
    totalEmployees: "إجمالي الموظفين",
    presentToday: "الحاضرون اليوم",
    onLeave: "في إجازة",
    pendingRequests: "طلبات معلقة",
    comingSoon: "قريباً",
    activeEmployees: "الموظفون النشطون",
    quickActions: "إجراءات سريعة",
    recentActivity: "النشاطات الأخيرة",
    noActivity: "لا يوجد نشاط بعد",
    noActivityDesc: "سيظهر هنا سجل النشاطات قريباً",
    welcome: "مرحباً",
    overview: "نظرة عامة على",
    // Shared
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    cancel: "إلغاء",
    save: "حفظ",
    saving: "جارِ الحفظ...",
    create: "إنشاء",
    noResults: "لم يتم العثور على نتائج",
    active: "نشط",
    inactive: "غير نشط",
    employee_count: "موظف",
    average: "متوسط",
    total: "إجمالي",
    // Departments
    addDepartment: "إضافة قسم",
    departmentsTitle: "الأقسام",
    departmentsDesc: "إدارة الأقسام في الشركة",
    totalDepartments: "إجمالي الأقسام",
    avgEmployeesPerDept: "متوسط الموظفين/قسم",
    searchDepartments: "بحث في الأقسام...",
    noDepartments: "لا يوجد أقسام بعد",
    addFirstDept: "إضافة أول قسم",
    addDeptTitle: "إضافة قسم جديد",
    addDeptDesc: "أدخل بيانات القسم الجديد",
    deptNameAr: "اسم القسم بالعربي *",
    deptNameEn: "اسم القسم بالإنجليزي",
    deptDesc: "الوصف",
    deptDescPlaceholder: "وصف مختصر للقسم...",
    createDept: "إنشاء القسم",
    failedLoad: "فشل تحميل البيانات",
    failedCreate: "فشل إنشاء القسم",
    createdSuccess: "تم إنشاء القسم بنجاح",
    nameArRequired: "اسم القسم بالعربي مطلوب",
    // Branches
    addBranch: "إضافة فرع",
    branchesTitle: "الفروع",
    branchesDesc: "إدارة فروع الشركة",
    totalBranches: "إجمالي الفروع",
    avgEmployeesPerBranch: "متوسط الموظفين/فرع",
    searchBranches: "بحث في الفروع...",
    noBranches: "لا يوجد فروع بعد",
    addFirstBranch: "إضافة أول فرع",
    addBranchTitle: "إضافة فرع جديد",
    addBranchDesc: "أدخل بيانات الفرع الجديد",
    branchNameAr: "اسم الفرع بالعربي *",
    branchNameEn: "اسم الفرع بالإنجليزي",
    branchAddress: "العنوان",
    branchPhone: "رقم الهاتف",
    createBranch: "إنشاء الفرع",
    mainBranch: "فرع رئيسي",
    failedCreateBranch: "فشل إنشاء الفرع",
    createdBranchSuccess: "تم إنشاء الفرع بنجاح",
    branchNameArRequired: "اسم الفرع بالعربي مطلوب",
    // Shifts
    addShift: "إضافة شيفت",
    shiftsTitle: "الشيفتات",
    shiftsDesc: "إدارة شيفتات العمل",
    totalShifts: "إجمالي الشيفتات",
    defaultShift: "الشيفت الافتراضي",
    activeShifts: "النشطة",
    searchShifts: "بحث في الشيفتات...",
    noShifts: "لا يوجد شيفتات بعد",
    addFirstShift: "إضافة أول شيفت",
    shiftFixed: "ثابت",
    shiftFlex: "مرن",
    shiftOpen: "مفتوح",
    shiftStart: "البداية",
    shiftEnd: "النهاية",
    shiftHours: "ساعات",
    shiftGrace: "سماح",
    shiftBreak: "راحة",
    shiftMin: "د",
    assignEmployees: "تعيين موظفين",
    failedCreateShift: "فشل إنشاء الشيفت",
    createdShiftSuccess: "تم إنشاء الشيفت بنجاح",
    shiftNameRequired: "اسم الشيفت مطلوب",
    // Job Titles
    addJobTitle: "إضافة مسمى",
    jobTitlesTitle: "المسميات الوظيفية",
    jobTitlesDesc: "إدارة الوظائف والمناصب",
    totalJobTitles: "إجمالي المسميات",
    avgEmployeesPerTitle: "متوسط الموظفين/مسمى",
    searchJobTitles: "بحث في المسميات...",
    noJobTitles: "لا يوجد مسميات بعد",
    addFirstJobTitle: "إضافة أول مسمى",
    addJobTitleDialog: "إضافة مسمى وظيفي",
    addJobTitleDesc: "أدخل بيانات المسمى الجديد",
    jobTitleNameAr: "الاسم بالعربي *",
    jobTitleNameEn: "الاسم بالإنجليزي",
    jobTitleDescLabel: "الوصف",
    createJobTitle: "إنشاء",
    failedCreateTitle: "فشل الإنشاء",
    createdTitleSuccess: "تم إنشاء المسمى بنجاح",
    titleNameArRequired: "اسم المسمى بالعربي مطلوب",
    // Employees List
    employeesTitle: "الموظفون",
    employeesDesc: "إدارة جميع موظفي الشركة",
    activeEmployeesCount: "النشطون",
    inactiveEmployees: "غير نشط",
    importBtn: "استيراد",
    addEmployee: "إضافة موظف",
    searchEmployees: "بحث بالاسم، الكود، الموبايل، الرقم القومي...",
    allDepts: "كل الأقسام",
    allStatuses: "كل الحالات",
    statusActive: "نشط",
    statusInactive: "غير نشط",
    statusOnLeave: "في إجازة",
    statusTerminated: "منتهي",
    statusResigned: "مستقيل",
    colEmployee: "الموظف",
    colCode: "الكود",
    colDept: "القسم",
    colJobTitle: "المسمى الوظيفي",
    colBranch: "الفرع",
    colPhone: "الموبايل",
    colStatus: "الحالة",
    noEmployees: "لا يوجد موظفون",
    failedLoadEmployees: "فشل تحميل قائمة الموظفين",
    showingOf: "عرض",
    of: "من",
    ofTotal: "من إجمالي",
    deptFilter: "القسم",
    statusFilter: "الحالة",
    // Employee Detail
    employeeNotFound: "الموظف غير موجود",
    backToList: "العودة للقائمة",
    backToEmployees: "العودة للموظفين",
    personalInfo: "بيانات شخصية",
    jobInfo: "الوظيفة",
    salaryInfo: "المرتب",
    contractInfo: "العقد",
    nameAr: "الاسم بالعربي",
    nameEn: "الاسم بالإنجليزي",
    nationalId: "الرقم القومي",
    birthDate: "تاريخ الميلاد",
    gender: "النوع",
    maritalStatus: "الحالة الاجتماعية",
    religion: "الديانة",
    nationality: "الجنسية",
    contactInfo: "التواصل",
    phone: "الموبايل",
    phone2: "موبايل إضافي",
    email: "البريد الإلكتروني",
    city: "المدينة",
    addressField: "العنوان",
    empCode: "كود الموظف",
    hireDate: "تاريخ التعيين",
    dept: "القسم",
    branch: "الفرع",
    jobTitle: "المسمى الوظيفي",
    directManager: "المدير المباشر",
    attendancePattern: "نمط الحضور",
    workerType: "تصنيف الموظف",
    empStatus: "الحالة الوظيفية",
    basicSalary: "الراتب الأساسي",
    currency: "العملة",
    bankName: "البنك",
    bankAccount: "رقم الحساب",
    iban: "IBAN",
    contractType: "نوع العقد",
    contractStart: "بداية العقد",
    contractEnd: "نهاية العقد",
    // Import Page
    importTitle: "استيراد الموظفين",
    importDesc: "ارفع ملف Excel لإضافة أو تحديث موظفين بالجملة",
    uploadFile: "رفع الملف",
    downloadTemplate: "تحميل النموذج",
    dragDrop: "اسحب وأفلت الملف هنا",
    orClick: "أو اضغط للاختيار من الجهاز",
    maxSize: "حد أقصى 10 ميجا",
    startImport: "بدء الاستيراد",
    uploading: "جارِ الرفع...",
    importSuccess: "تم الاستيراد بنجاح",
    importFailed: "فشل الاستيراد",
    newEmployees: "موظف جديد",
    updatedEmployees: "تحديث",
    errors: "أخطاء",
    errorDetails: "تفاصيل الأخطاء",
    row: "صف",
    selectExcel: "يجب اختيار ملف Excel (.xlsx أو .xls)",
    fileTooLarge: "حجم الملف كبير جداً (الحد الأقصى 10 ميجا)",
    templateDownloaded: "تم تحميل النموذج بنجاح",
    templateFailed: "فشل تحميل النموذج",
    serverError: "خطأ في الاتصال بالسيرفر",
    upTo500: "حتى 500 موظف",
    perBatch: "في المرة الواحدة",
    fields67: "67 حقل",
    comprehensiveData: "بيانات شاملة لكل موظف",
    autoValidation: "تحقق تلقائي",
    validationDesc: "من صحة البيانات قبل الحفظ",
    kb: "كيلوبايت",
    importInstructions: "تعليمات الاستيراد",
    step1: "حمّل النموذج",
    step1Desc: "اضغط على تحميل النموذج للحصول على الشيت",
    step2: "املأ البيانات",
    step2Desc: "أدخل بيانات الموظفين في الشيت",
    step3: "ارفع الملف",
    step3Desc: "ارفع الملف المكتمل هنا",
    importNotes: "ملاحظات",
    note1: "الحقول المميزة بـ * إجبارية",
    note2: "الرقم القومي لازم يكون 14 رقم",
    note3: "التواريخ بصيغة YYYY-MM-DD",
    note4: "الموبايل بصيغة 01XXXXXXXXX",
    // Payroll
    payrollTitle: "الرواتب",
    payrollDesc: "إدارة رواتب الموظفين",
    selectMonth: "الشهر",
    selectYear: "السنة",
    grandTotalSalary: "إجمالي الرواتب",
    grandTotalAllowances: "إجمالي البدلات",
    grandTotalOvertime: "إجمالي الإضافي",
    grandTotalBonuses: "إجمالي المكافآت",
    grandTotalDeductions: "إجمالي الخصومات",
    grandTotalNet: "الصافي المستحق",
    empName: "اسم الموظف",
    basicSalaryCol: "الأساسي",
    allowancesCol: "البدلات",
    bonusesCol: "المكافآت",
    overtimeCol: "الإضافي",
    deductionsCol: "الخصومات",
    netSalaryCol: "الصافي",
    searchPayroll: "بحث بالاسم أو الكود...",
    noPayrollData: "لا يوجد بيانات رواتب لهذا الشهر",
    workingDays: "أيام العمل",
    presentDays: "أيام الحضور",
    absentDays: "أيام الغياب",
    lateMinutes: "دقائق التأخير",
    overtimeHours: "ساعات إضافية",
    onLeaveDays: "أيام إجازة",
    missionDays: "أيام مهمة",
    exportExcel: "تصدير Excel",
    exportPDF: "تصدير PDF",
    viewPayslip: "عرض كشف المرتب",
    payslipTitle: "كشف مرتب",
    forEmployee: "للموظف",
    forMonth: "لشهر",
    salaryBreakdown: "تفصيل الراتب",
    attendanceSummary: "ملخص الحضور",
    deductionsBreakdown: "تفصيل الخصومات",
    lateDeduction: "خصم التأخير",
    absenceDeduction: "خصم الغياب",
    earlyLeaveDeduction: "خصم الانصراف المبكر",
    insuranceDeduction: "خصم التأمين",
    installments: "أقساط",
    penalties: "جزاءات",
    extraDeductions: "خصومات إضافية",
    nightAllowance: "بدل ليلي",
    weekendAllowance: "بدل نهاية الأسبوع",
    fieldAllowance: "بدل ميداني",
    grossSalary: "الراتب الإجمالي",
    monthlyComparison: "مقارنة شهرية",
    monthlyComparisonDesc: "مقارنة الرواتب بين الشهور",
    advancedFilters: "فلاتر متقدمة",
    filterByBranch: "فلترة حسب الفرع",
    filterByDept: "فلترة حسب القسم",
    payrollAnalytics: "تحليلات الرواتب",
    salaryDistribution: "توزيع الرواتب",
    topPaid: "أعلى رواتب",
    payrollTrends: "اتجاهات الرواتب",
    bulkPayment: "دفع جماعي",
    processPayment: "معالجة الدفع",
    January: "يناير",
    February: "فبراير",
    March: "مارس",
    April: "أبريل",
    May: "مايو",
    June: "يونيو",
    July: "يوليو",
    August: "أغسطس",
    September: "سبتمبر",
    October: "أكتوبر",
    November: "نوفمبر",
    December: "ديسمبر",
    // Footer
    designedBy: "Designed by",
    designedByName: "Eng/John Samir | JS Solutions",
  },
  en: {
    // Sidebar
    dashboard: "Dashboard",
    employees: "Employees",
    attendance: "Attendance",
    leaves: "Leaves",
    requests: "Requests",
    payroll: "Payroll",
    missions: "Missions",
    locations: "Live Locations",
    announcements: "Announcements",
    departments: "Departments",
    branches: "Branches",
    shifts: "Shifts",
    jobTitles: "Job Titles",
    company: "Company",
    settings: "Settings",
    importEmployees: "Import Employees",
    // Header
    logout: "Logout",
    profile: "Profile",
    search: "Quick search...",
    // Dashboard
    totalEmployees: "Total Employees",
    presentToday: "Present Today",
    onLeave: "On Leave",
    pendingRequests: "Pending Requests",
    comingSoon: "Coming Soon",
    activeEmployees: "Active Employees",
    quickActions: "Quick Actions",
    recentActivity: "Recent Activity",
    noActivity: "No activity yet",
    noActivityDesc: "Activity log will appear here soon",
    welcome: "Welcome",
    overview: "Overview of",
    // Shared
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving...",
    create: "Create",
    noResults: "No results found",
    active: "Active",
    inactive: "Inactive",
    employee_count: "employees",
    average: "Average",
    total: "Total",
    // Departments
    addDepartment: "Add Department",
    departmentsTitle: "Departments",
    departmentsDesc: "Manage company departments",
    totalDepartments: "Total Departments",
    avgEmployeesPerDept: "Avg Employees/Dept",
    searchDepartments: "Search departments...",
    noDepartments: "No departments yet",
    addFirstDept: "Add First Department",
    addDeptTitle: "Add New Department",
    addDeptDesc: "Enter department details",
    deptNameAr: "Arabic Name *",
    deptNameEn: "English Name",
    deptDesc: "Description",
    deptDescPlaceholder: "Brief description...",
    createDept: "Create Department",
    failedLoad: "Failed to load data",
    failedCreate: "Failed to create department",
    createdSuccess: "Department created successfully",
    nameArRequired: "Arabic name is required",
    // Branches
    addBranch: "Add Branch",
    branchesTitle: "Branches",
    branchesDesc: "Manage company branches",
    totalBranches: "Total Branches",
    avgEmployeesPerBranch: "Avg Employees/Branch",
    searchBranches: "Search branches...",
    noBranches: "No branches yet",
    addFirstBranch: "Add First Branch",
    addBranchTitle: "Add New Branch",
    addBranchDesc: "Enter branch details",
    branchNameAr: "Arabic Name *",
    branchNameEn: "English Name",
    branchAddress: "Address",
    branchPhone: "Phone Number",
    createBranch: "Create Branch",
    mainBranch: "Main Branch",
    failedCreateBranch: "Failed to create branch",
    createdBranchSuccess: "Branch created successfully",
    branchNameArRequired: "Arabic branch name is required",
    // Shifts
    addShift: "Add Shift",
    shiftsTitle: "Shifts",
    shiftsDesc: "Manage work shifts",
    totalShifts: "Total Shifts",
    defaultShift: "Default Shift",
    activeShifts: "Active",
    searchShifts: "Search shifts...",
    noShifts: "No shifts yet",
    addFirstShift: "Add First Shift",
    shiftFixed: "Fixed",
    shiftFlex: "Flexible",
    shiftOpen: "Open",
    shiftStart: "Start",
    shiftEnd: "End",
    shiftHours: "Hours",
    shiftGrace: "Grace",
    shiftBreak: "Break",
    shiftMin: "min",
    assignEmployees: "Assign Employees",
    failedCreateShift: "Failed to create shift",
    createdShiftSuccess: "Shift created successfully",
    shiftNameRequired: "Shift name is required",
    // Job Titles
    addJobTitle: "Add Job Title",
    jobTitlesTitle: "Job Titles",
    jobTitlesDesc: "Manage positions and roles",
    totalJobTitles: "Total Job Titles",
    avgEmployeesPerTitle: "Avg Employees/Title",
    searchJobTitles: "Search job titles...",
    noJobTitles: "No job titles yet",
    addFirstJobTitle: "Add First Job Title",
    addJobTitleDialog: "Add Job Title",
    addJobTitleDesc: "Enter job title details",
    jobTitleNameAr: "Arabic Name *",
    jobTitleNameEn: "English Name",
    jobTitleDescLabel: "Description",
    createJobTitle: "Create",
    failedCreateTitle: "Failed to create",
    createdTitleSuccess: "Job title created successfully",
    titleNameArRequired: "Arabic name is required",
    // Employees List
    employeesTitle: "Employees",
    employeesDesc: "Manage all company employees",
    activeEmployeesCount: "Active",
    inactiveEmployees: "Inactive",
    importBtn: "Import",
    addEmployee: "Add Employee",
    searchEmployees: "Search by name, code, phone, national ID...",
    allDepts: "All Departments",
    allStatuses: "All Statuses",
    statusActive: "Active",
    statusInactive: "Inactive",
    statusOnLeave: "On Leave",
    statusTerminated: "Terminated",
    statusResigned: "Resigned",
    colEmployee: "Employee",
    colCode: "Code",
    colDept: "Department",
    colJobTitle: "Job Title",
    colBranch: "Branch",
    colPhone: "Phone",
    colStatus: "Status",
    noEmployees: "No employees found",
    failedLoadEmployees: "Failed to load employees",
    showingOf: "Showing",
    of: "of",
    ofTotal: "of total",
    deptFilter: "Department",
    statusFilter: "Status",
    // Employee Detail
    employeeNotFound: "Employee not found",
    backToList: "Back to list",
    backToEmployees: "Back to employees",
    personalInfo: "Personal Info",
    jobInfo: "Job Info",
    salaryInfo: "Salary",
    contractInfo: "Contract",
    nameAr: "Arabic Name",
    nameEn: "English Name",
    nationalId: "National ID",
    birthDate: "Date of Birth",
    gender: "Gender",
    maritalStatus: "Marital Status",
    religion: "Religion",
    nationality: "Nationality",
    contactInfo: "Contact",
    phone: "Phone",
    phone2: "Secondary Phone",
    email: "Email",
    city: "City",
    addressField: "Address",
    empCode: "Employee Code",
    hireDate: "Hire Date",
    dept: "Department",
    branch: "Branch",
    jobTitle: "Job Title",
    directManager: "Direct Manager",
    attendancePattern: "Attendance Pattern",
    workerType: "Worker Type",
    empStatus: "Employment Status",
    basicSalary: "Basic Salary",
    currency: "Currency",
    bankName: "Bank",
    bankAccount: "Account Number",
    iban: "IBAN",
    contractType: "Contract Type",
    contractStart: "Contract Start",
    contractEnd: "Contract End",
    // Import Page
    importTitle: "Import Employees",
    importDesc: "Upload an Excel file to add or update employees in bulk",
    uploadFile: "Upload File",
    downloadTemplate: "Download Template",
    dragDrop: "Drag and drop file here",
    orClick: "or click to browse",
    maxSize: "Max 10 MB",
    startImport: "Start Import",
    uploading: "Uploading...",
    importSuccess: "Import successful",
    importFailed: "Import failed",
    newEmployees: "new employees",
    updatedEmployees: "updated",
    errors: "errors",
    errorDetails: "Error Details",
    row: "Row",
    selectExcel: "Please select an Excel file (.xlsx or .xls)",
    fileTooLarge: "File too large (max 10 MB)",
    templateDownloaded: "Template downloaded successfully",
    templateFailed: "Failed to download template",
    serverError: "Server connection error",
    upTo500: "Up to 500 employees",
    perBatch: "per batch",
    fields67: "67 fields",
    comprehensiveData: "Comprehensive data per employee",
    autoValidation: "Auto validation",
    validationDesc: "Data validated before saving",
    kb: "KB",
    importInstructions: "Import Instructions",
    step1: "Download Template",
    step1Desc: "Click download template to get the sheet",
    step2: "Fill Data",
    step2Desc: "Enter employee data in the sheet",
    step3: "Upload File",
    step3Desc: "Upload the completed file here",
    importNotes: "Notes",
    note1: "Fields marked * are required",
    note2: "National ID must be 14 digits",
    note3: "Dates in YYYY-MM-DD format",
    note4: "Phone in 01XXXXXXXXX format",
    // Payroll
    payrollTitle: "Payroll",
    payrollDesc: "Manage employee payroll",
    selectMonth: "Month",
    selectYear: "Year",
    grandTotalSalary: "Total Salaries",
    grandTotalAllowances: "Total Allowances",
    grandTotalOvertime: "Total Overtime",
    grandTotalBonuses: "Total Bonuses",
    grandTotalDeductions: "Total Deductions",
    grandTotalNet: "Net Payable",
    empName: "Employee Name",
    basicSalaryCol: "Basic",
    allowancesCol: "Allowances",
    bonusesCol: "Bonuses",
    overtimeCol: "Overtime",
    deductionsCol: "Deductions",
    netSalaryCol: "Net",
    searchPayroll: "Search by name or code...",
    noPayrollData: "No payroll data for this month",
    workingDays: "Working Days",
    presentDays: "Present Days",
    absentDays: "Absent Days",
    lateMinutes: "Late Minutes",
    overtimeHours: "Overtime Hours",
    onLeaveDays: "Leave Days",
    missionDays: "Mission Days",
    exportExcel: "Export Excel",
    exportPDF: "Export PDF",
    viewPayslip: "View Payslip",
    payslipTitle: "Payslip",
    forEmployee: "For",
    forMonth: "For Month",
    salaryBreakdown: "Salary Breakdown",
    attendanceSummary: "Attendance Summary",
    deductionsBreakdown: "Deductions Breakdown",
    lateDeduction: "Late Deduction",
    absenceDeduction: "Absence Deduction",
    earlyLeaveDeduction: "Early Leave Deduction",
    insuranceDeduction: "Insurance",
    installments: "Installments",
    penalties: "Penalties",
    extraDeductions: "Extra Deductions",
    nightAllowance: "Night Allowance",
    weekendAllowance: "Weekend Allowance",
    fieldAllowance: "Field Allowance",
    grossSalary: "Gross Salary",
    monthlyComparison: "Monthly Comparison",
    monthlyComparisonDesc: "Compare payroll between months",
    advancedFilters: "Advanced Filters",
    filterByBranch: "Filter by Branch",
    filterByDept: "Filter by Department",
    payrollAnalytics: "Payroll Analytics",
    salaryDistribution: "Salary Distribution",
    topPaid: "Top Paid",
    payrollTrends: "Payroll Trends",
    bulkPayment: "Bulk Payment",
    processPayment: "Process Payment",
    January: "January",
    February: "February",
    March: "March",
    April: "April",
    May: "May",
    June: "June",
    July: "July",
    August: "August",
    September: "September",
    October: "October",
    November: "November",
    December: "December",
    // Footer
    designedBy: "Designed by",
    designedByName: "Eng/John Samir | JS Solutions",
  },
} as const;

export type DictKey = keyof typeof dict.ar;

export function useDict() {
  const lang = useLangStore((s) => s.lang);
  return dict[lang];
}
