"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus, User, CheckCircle2, Copy, MessageCircle, Smartphone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useLangStore } from "@/lib/stores/language";
import { STORAGE_KEYS } from "@/lib/constants/config";

interface Dept     { id: number; name?: string; name_ar?: string; name_en?: string }
interface Branch   { id: number; name?: string; name_ar?: string; name_en?: string }
interface JobTitle { id: number; title?: string; title_ar?: string; title_en?: string; name?: string; name_ar?: string; name_en?: string }
interface Manager  { id: number; full_name?: string; name?: string }

interface Props {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  departments: Dept[];
  branches: Branch[];
  jobTitles: JobTitle[];
  managers?: Manager[];
}

const EMPTY = {
  full_name_ar: "", full_name_en: "",
  phone: "", email: "", national_id: "", birth_date: "",
  gender: "male", marital_status: "single",
  employee_code: "", // auto-generated by backendhire_date: "",
  branch_id: "", department_id: "", job_title_id: "", direct_manager_id: "",
  worker_type: "office",
  contract_type: "permanent", contract_end_date: "",
  basic_salary: "",
  salary_payment_method: "cash",
  bank_name: "", bank_account: "",
  instapay_phone: "", wallet_phone: "", wallet_provider: "",
  has_insurance: "false", insurance_number: "", insurance_base_salary: "",
  address: "",
};

function Field({ label, value, onChange, type = "text", placeholder = "" }: {
  label: string; value: string; onChange: (v: string) => void; type?: string; placeholder?: string;
}) {
  return (
    <div>
      <label className="text-sm font-medium mb-1 block">{label}</label>
      <Input type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} />
    </div>
  );
}

function Sel({ label, value, onChange, children }: {
  label: string; value: string; onChange: (v: string) => void; children: React.ReactNode;
}) {
  return (
    <div>
      <label className="text-sm font-medium mb-1 block">{label}</label>
      <select value={value} onChange={e => onChange(e.target.value)}
        className="w-full border border-border rounded-md px-3 py-2 text-sm bg-background">
        {children}
      </select>
    </div>
  );
}

function Section({ title }: { title: string }) {
  return <p className="text-xs font-semibold text-muted-foreground uppercase mb-3 mt-2">{title}</p>;
}

export function CreateEmployeeDialog({ open, onClose, onSuccess, departments, branches, jobTitles, managers = [] }: Props) {
  const lang = useLangStore((s) => s.lang);
  const [form, setForm] = useState({ ...EMPTY });
  const [loading, setLoading] = useState(false);
  const [employeeCredentials, setEmployeeCredentials] = useState<any>(null);
  const ar = lang === "ar";

  const token = typeof window !== "undefined" ? localStorage.getItem(STORAGE_KEYS.token) : null;
  const authHeader = token?.startsWith("Token") ? token : `Token ${token}`;
  const set = (k: string, v: string) => setForm(p => ({ ...p, [k]: v }));

  const pick = (obj: any, keys: string[]) => {
    for (const k of keys) { if (typeof obj?.[k] === "string" && obj[k].trim()) return obj[k]; }
    return "";
  };
  const dLabel = (d: Dept)     => ar ? pick(d, ["name","name_ar","name_en"]) : pick(d, ["name_en","name","name_ar"]);
  const bLabel = (b: Branch)   => ar ? pick(b, ["name","name_ar","name_en"]) : pick(b, ["name_en","name","name_ar"]);
  const jLabel = (j: JobTitle) => ar ? pick(j, ["title","name","title_ar","name_ar","title_en","name_en"]) : pick(j, ["title_en","name_en","title","name"]);
  const mLabel = (m: Manager)  => m.full_name || m.name || String(m.id);

  const handleSubmit = async () => {
    if (!form.full_name_ar || !form.full_name_en || !form.phone || !form.national_id || !form.birth_date || !form.hire_date) {
      toast.error(ar ? "يرجى ملء جميع الحقول المطلوبة" : "Please fill all required fields");
      return;
    }

    // نقسم الاسم لأول + وسط + أخير
    const splitName = (fullName: string) => {
      const parts = fullName.trim().split(/\s+/);
      if (parts.length === 0) return { first: "", middle: "", last: "" };
      if (parts.length === 1) return { first: parts[0], middle: "", last: parts[0] };
      if (parts.length === 2) return { first: parts[0], middle: "", last: parts[1] };
      return {
        first: parts[0],
        middle: parts.slice(1, -1).join(" "),
        last: parts[parts.length - 1]
      };
    };
    const nameAR = splitName(form.full_name_ar);
    const nameEN = splitName(form.full_name_en);
    setLoading(true);
    try {
      const payload: any = {
        first_name_ar: nameAR.first,
        middle_name_ar: nameAR.middle || undefined,
        last_name_ar: nameAR.last,
        first_name_en: nameEN.first,
        last_name_en: nameEN.last,
        phone: form.phone,
        email: form.email || undefined,
        national_id: form.national_id,
        birth_date: form.birth_date,
        gender: form.gender,
        marital_status: form.marital_status,
        hire_date: form.hire_date,
        // employee_code: auto-generated by backend
        branch_id: form.branch_id ? Number(form.branch_id) : undefined,
        department_id: form.department_id ? Number(form.department_id) : undefined,
        job_title_id: form.job_title_id ? Number(form.job_title_id) : undefined,
        direct_manager_id: form.direct_manager_id ? Number(form.direct_manager_id) : undefined,
        worker_type: form.worker_type,
        contract_type: form.contract_type,
        contract_end_date: form.contract_end_date || undefined,
        basic_salary: form.basic_salary ? Number(form.basic_salary) : 0,
        salary_payment_method: form.salary_payment_method,
        bank_name: form.bank_name || undefined,
        bank_account: form.bank_account || undefined,
        instapay_phone: form.instapay_phone || undefined,
        wallet_phone: form.wallet_phone || undefined,
        wallet_provider: form.wallet_provider || undefined,
        has_insurance: form.has_insurance === "true",
        insurance_number: form.insurance_number || undefined,
        insurance_base_salary: form.insurance_base_salary ? Number(form.insurance_base_salary) : null,
        address: form.address || undefined,
      };

      const res = await fetch("/api/hr/employees/create", {
        method: "POST",
        headers: { Authorization: authHeader, "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (res.ok) {
        toast.success(ar ? "تم إضافة الموظف بنجاح" : "Employee added");

        // عرض بطاقة تعليمات التفعيل
        const empData = data?.employee || data?.data || data;
        const lastFourNID = form.national_id ? form.national_id.slice(-4) : "";
        setEmployeeCredentials({
          name: `${form.full_name_ar || form.first_name_ar} ${form.last_name_ar || ""}`.trim(),
          phone: form.phone,
          national_id_last4: lastFourNID,
          employee_code: empData?.employee_code || "",
        });

        setForm({ ...EMPTY });
        onSuccess();
        // مش نقفل الـ dialog عشان تظهر البطاقة
      } else {
        toast.error(data.error || data.message || data.detail || JSON.stringify(data));
      }
    } catch {
      toast.error(ar ? "خطأ في الشبكة" : "Network error");
    } finally {
      setLoading(false);
    }
  };

  const showBank      = form.salary_payment_method === "bank";
  const showInstapay  = form.salary_payment_method === "instapay";
  const showWallet    = form.salary_payment_method === "wallet";
  const showInsurance = form.has_insurance === "true";
  const showContractEnd = form.contract_type === "temporary" || form.contract_type === "training";

  if (employeeCredentials) {
    const activationMessage = ar
      ? `مرحباً ${employeeCredentials.name}!\n\nتم إنشاء حسابك في MotionHR.\n\nخطوات التفعيل:\n1. حمّل تطبيق MotionHR\n2. افتح التطبيق واختر "تفعيل الحساب"\n3. أدخل:\n   - رقم موبايلك: ${employeeCredentials.phone}\n   - آخر 4 أرقام من رقمك القومي: ${employeeCredentials.national_id_last4}\n4. اختر كلمة مرور جديدة\n\nكود الموظف: ${employeeCredentials.employee_code}`
      : `Welcome ${employeeCredentials.name}!\n\nActivation:\n1. Download MotionHR app\n2. Choose "Activate Account"\n3. Enter:\n   - Phone: ${employeeCredentials.phone}\n   - Last 4 of National ID: ${employeeCredentials.national_id_last4}\n\nEmployee Code: ${employeeCredentials.employee_code}`;

    return (
      <Dialog open={open} onOpenChange={v => !v && (setEmployeeCredentials(null), onClose())}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-emerald-600">
              <CheckCircle2 className="w-6 h-6" />
              {ar ? "تم إضافة الموظف بنجاح" : "Employee Added"}
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4 pt-2">
            <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4">
              <p className="font-bold text-emerald-800 mb-2">{employeeCredentials.name}</p>
              <p className="text-xs text-emerald-700">
                {ar ? "كود الموظف:" : "Employee Code:"} <span className="font-mono font-bold">{employeeCredentials.employee_code}</span>
              </p>
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
              <div className="flex items-center gap-2 mb-3">
                <Smartphone className="w-5 h-5 text-blue-600" />
                <p className="font-bold text-blue-900">
                  {ar ? "بيانات تفعيل الحساب" : "Activation Credentials"}
                </p>
              </div>

              <div className="space-y-2 text-sm">
                <div className="flex items-center justify-between bg-white p-2 rounded">
                  <span className="text-slate-600">{ar ? "رقم الموبايل:" : "Phone:"}</span>
                  <span className="font-mono font-bold" dir="ltr">{employeeCredentials.phone}</span>
                </div>
                <div className="flex items-center justify-between bg-white p-2 rounded">
                  <span className="text-slate-600">{ar ? "آخر 4 من القومي:" : "Last 4 of NID:"}</span>
                  <span className="font-mono font-bold text-lg text-blue-600">{employeeCredentials.national_id_last4}</span>
                </div>
              </div>

              <p className="text-xs text-blue-700 mt-3">
                {ar ? "💡 الموظف يستخدم البيانات دي في التطبيق للتفعيل، ثم يختار كلمة سر جديدة" : "💡 Employee uses these credentials to activate in the app"}
              </p>
            </div>

            <div className="flex flex-wrap gap-2">
              <Button
                onClick={() => {
                  navigator.clipboard.writeText(activationMessage);
                  toast.success(ar ? "تم النسخ ✓" : "Copied ✓");
                }}
                variant="outline"
                className="flex-1 gap-2"
              >
                <Copy className="w-4 h-4" />
                {ar ? "نسخ التعليمات" : "Copy"}
              </Button>

              <Button
                onClick={() => {
                  const encoded = encodeURIComponent(activationMessage);
                  const phone = employeeCredentials.phone.replace(/^0/, "20");
                  window.open(`https://wa.me/${phone}?text=${encoded}`, "_blank");
                }}
                className="flex-1 gap-2 bg-green-600 hover:bg-green-700"
              >
                <MessageCircle className="w-4 h-4" />
                {ar ? "إرسال واتساب" : "WhatsApp"}
              </Button>
            </div>

            <Button
              onClick={() => { setEmployeeCredentials(null); onClose(); }}
              variant="outline"
              className="w-full"
            >
              {ar ? "تم / إغلاق" : "Done"}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  return (
    <Dialog open={open} onOpenChange={v => !v && onClose()}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <User className="w-5 h-5 text-brand-primary" />
            {ar ? "إضافة موظف جديد" : "Add New Employee"}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 pt-2">

          {/* الاسم */}
          <Section title={ar ? "الاسم" : "Name"} />
          <div className="grid grid-cols-2 gap-3">
            <Field
              label={ar ? "الاسم الكامل بالعربي *" : "Full Name (Arabic) *"}
              value={form.full_name_ar}
              onChange={v => set("full_name_ar", v)}
              placeholder={ar ? "محمد أحمد علي" : "محمد أحمد علي"}
            />
            <Field
              label={ar ? "الاسم الكامل بالإنجليزي *" : "Full Name (English) *"}
              value={form.full_name_en}
              onChange={v => set("full_name_en", v)}
              placeholder="Mohamed Ahmed Ali"
            />
          </div>
          <p className="text-xs text-muted-foreground -mt-2">
            {ar ? "💡 اكتب الاسم كامل مفصول بمسافات، النظام هيقسمه تلقائياً" : "💡 Enter full name with spaces, system will split automatically"}
          </p>

          {/* البيانات الأساسية */}
          <Section title={ar ? "البيانات الأساسية" : "Basic Info"} />
          <div className="grid grid-cols-2 gap-3">
            <Field label={ar ? "رقم الموبايل / واتساب *" : "Phone / WhatsApp *"} value={form.phone} onChange={v => set("phone", v)} placeholder="01012345678" />
            <Field label={ar ? "البريد الإلكتروني" : "Email"} value={form.email} onChange={v => set("email", v)} type="email" placeholder="emp@co.com" />
            <Field label={ar ? "الرقم القومي *" : "National ID *"} value={form.national_id} onChange={v => set("national_id", v)} placeholder="29501011234567" />
            <Field label={ar ? "تاريخ الميلاد *" : "Birth Date *"} value={form.birth_date} onChange={v => set("birth_date", v)} type="date" />
            <Sel label={ar ? "الجنس" : "Gender"} value={form.gender} onChange={v => set("gender", v)}>
              <option value="male">{ar ? "ذكر" : "Male"}</option>
              <option value="female">{ar ? "أنثى" : "Female"}</option>
            </Sel>
            <Sel label={ar ? "الحالة الاجتماعية" : "Marital Status"} value={form.marital_status} onChange={v => set("marital_status", v)}>
              <option value="single">{ar ? "أعزب" : "Single"}</option>
              <option value="married">{ar ? "متزوج" : "Married"}</option>
              <option value="divorced">{ar ? "مطلق" : "Divorced"}</option>
              <option value="widowed">{ar ? "أرمل" : "Widowed"}</option>
            </Sel>
            <Field label={ar ? "العنوان" : "Address"} value={form.address} onChange={v => set("address", v)} placeholder={ar ? "القاهرة، مصر" : "Cairo, Egypt"} />
          </div>

          {/* بيانات وظيفية */}
          <Section title={ar ? "البيانات الوظيفية" : "Job Info"} />
          <div className="grid grid-cols-2 gap-3">            <Field label={ar ? "تاريخ التعيين *" : "Hire Date *"} value={form.hire_date} onChange={v => set("hire_date", v)} type="date" />
            <Sel label={ar ? "الفرع" : "Branch"} value={form.branch_id} onChange={v => set("branch_id", v)}>
              <option value="">{ar ? "اختر..." : "Select..."}</option>
              {branches.map(b => <option key={b.id} value={b.id}>{bLabel(b)}</option>)}
            </Sel>
            <Sel label={ar ? "القسم" : "Department"} value={form.department_id} onChange={v => set("department_id", v)}>
              <option value="">{ar ? "اختر..." : "Select..."}</option>
              {departments.map(d => <option key={d.id} value={d.id}>{dLabel(d)}</option>)}
            </Sel>
            <Sel label={ar ? "المسمى الوظيفي" : "Job Title"} value={form.job_title_id} onChange={v => set("job_title_id", v)}>
              <option value="">{ar ? "اختر..." : "Select..."}</option>
              {jobTitles.map(j => <option key={j.id} value={j.id}>{jLabel(j)}</option>)}
            </Sel>
            <Sel label={ar ? "المدير المباشر" : "Direct Manager"} value={form.direct_manager_id} onChange={v => set("direct_manager_id", v)}>
              <option value="">{ar ? "بدون مدير" : "No Manager"}</option>
              {managers.map(m => <option key={m.id} value={m.id}>{mLabel(m)}</option>)}
            </Sel>
            <Sel label={ar ? "نوع الموظف" : "Worker Type"} value={form.worker_type} onChange={v => set("worker_type", v)}>
              <option value="office">{ar ? "مكتبي" : "Office"}</option>
              <option value="field_free">{ar ? "ميداني حر" : "Field Free"}</option>
              <option value="field_assigned">{ar ? "ميداني محدد" : "Field Assigned"}</option>
            </Sel>
          </div>

          {/* العقد */}
          <Section title={ar ? "العقد" : "Contract"} />
          <div className="grid grid-cols-2 gap-3">
            <Sel label={ar ? "نوع العقد" : "Contract Type"} value={form.contract_type} onChange={v => set("contract_type", v)}>
              <option value="permanent">{ar ? "دائم" : "Permanent"}</option>
              <option value="temporary">{ar ? "مؤقت" : "Temporary"}</option>
              <option value="training">{ar ? "تدريب" : "Training"}</option>
            </Sel>
            {showContractEnd && (
              <Field label={ar ? "تاريخ نهاية العقد" : "Contract End Date"} value={form.contract_end_date} onChange={v => set("contract_end_date", v)} type="date" />
            )}
          </div>

          {/* المرتب */}
          <Section title={ar ? "المرتب وطريقة القبض" : "Salary & Payment"} />
          <div className="grid grid-cols-2 gap-3">
            <Field label={ar ? "الراتب الأساسي" : "Basic Salary"} value={form.basic_salary} onChange={v => set("basic_salary", v)} type="number" placeholder="0" />
            <Sel label={ar ? "طريقة القبض" : "Payment Method"} value={form.salary_payment_method} onChange={v => set("salary_payment_method", v)}>
              <option value="cash">{ar ? "كاش" : "Cash"}</option>
              <option value="bank">{ar ? "بنك" : "Bank"}</option>
              <option value="instapay">{ar ? "انستاباي" : "InstaPay"}</option>
              <option value="wallet">{ar ? "محفظة" : "Wallet"}</option>
            </Sel>
            {showBank && <>
              <Field label={ar ? "اسم البنك" : "Bank Name"} value={form.bank_name} onChange={v => set("bank_name", v)} placeholder={ar ? "البنك الأهلي" : "National Bank"} />
              <Field label={ar ? "رقم الحساب" : "Account Number"} value={form.bank_account} onChange={v => set("bank_account", v)} placeholder="1234567890" />
            </>}
            {showInstapay && (
              <Field label={ar ? "رقم انستاباي" : "InstaPay Phone"} value={form.instapay_phone} onChange={v => set("instapay_phone", v)} placeholder="01012345678" />
            )}
            {showWallet && <>
              <Field label={ar ? "رقم المحفظة" : "Wallet Phone"} value={form.wallet_phone} onChange={v => set("wallet_phone", v)} placeholder="01012345678" />
              <Field label={ar ? "مزود المحفظة" : "Wallet Provider"} value={form.wallet_provider} onChange={v => set("wallet_provider", v)} placeholder="Vodafone Cash" />
            </>}
          </div>

          {/* التأمين */}
          <Section title={ar ? "التأمين" : "Insurance"} />
          <div className="grid grid-cols-2 gap-3">
            <Sel label={ar ? "مؤمن عليه؟" : "Has Insurance?"} value={form.has_insurance} onChange={v => set("has_insurance", v)}>
              <option value="false">{ar ? "لا" : "No"}</option>
              <option value="true">{ar ? "نعم" : "Yes"}</option>
            </Sel>
            {showInsurance && (
              <>
                <Field label={ar ? "رقم التأمين" : "Insurance Number"} value={form.insurance_number} onChange={v => set("insurance_number", v)} placeholder="123456789" />
                <Field label={ar ? "المرتب التأميني الخاص" : "Insurance Base Salary"} value={form.insurance_base_salary} onChange={v => set("insurance_base_salary", v)} placeholder={ar ? "اختياري - للسياسات المخصصة" : "Optional"} />
              </>
            )}
          </div>

          {/* أزرار */}
          <div className="flex gap-3 pt-3 border-t">
            <Button onClick={handleSubmit} disabled={loading} className="flex-1 bg-brand-primary hover:bg-brand-secondary gap-2">
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
              {ar ? "إضافة الموظف" : "Add Employee"}
            </Button>
            <Button variant="outline" onClick={onClose} className="flex-1">
              {ar ? "إلغاء" : "Cancel"}
            </Button>
          </div>

        </div>
      </DialogContent>
    </Dialog>
  );
}







